import { jsPDF } from "jspdf";

type Field = { label: string; value: string | number | null | undefined };
type LineItem = { description: string; quantity: string | number; unit: string; amount: string | number; specification?: string | null };

const money = (value: string | number | null | undefined) => `PHP ${Number(value || 0).toLocaleString("en-PH", { minimumFractionDigits: 2 })}`;
const date = (value: Date | string | null | undefined) => value ? new Date(value).toLocaleDateString("en-PH") : "—";

export function officialFormFileName(kind: "purchase_request" | "pre_canvass" | "abstract" | "purchase_order", recordNumber: string) {
  const suffix = { purchase_request: "Appendix60", pre_canvass: "AnnexD", abstract: "AnnexF", purchase_order: "Appendix61" }[kind];
  return `${recordNumber}_${suffix}.pdf`;
}

export function invokeOfficialPdfDownload(doc: Pick<jsPDF, "save">, fileName: string) {
  doc.save(fileName);
}

function createDocument(title: string, subtitle: string) {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  doc.setFillColor(123, 30, 30);
  doc.rect(0, 0, 210, 18, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.text("BATANES STATE COLLEGE", 14, 8);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(7.5);
  doc.text("ProcureWise · Offline record copy", 14, 13);
  doc.setTextColor(32, 40, 51);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(16);
  doc.text(title, 14, 29);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(100, 84, 49);
  doc.text(subtitle, 14, 35);
  return { doc, y: 43 };
}

function fields(doc: jsPDF, y: number, entries: Field[]) {
  let cursor = y;
  for (let index = 0; index < entries.length; index += 2) {
    const row = entries.slice(index, index + 2);
    row.forEach((entry, column) => {
      const x = column === 0 ? 14 : 108;
      doc.setDrawColor(225, 220, 210);
      doc.rect(x, cursor, 88, 15);
      doc.setFont("helvetica", "bold");
      doc.setFontSize(7);
      doc.setTextColor(123, 30, 30);
      doc.text(entry.label.toUpperCase(), x + 3, cursor + 4.5);
      doc.setFont("helvetica", "normal");
      doc.setFontSize(9);
      doc.setTextColor(48, 57, 70);
      const text = String(entry.value ?? "—");
      const lines = doc.splitTextToSize(text, 81);
      doc.text(lines.slice(0, 2), x + 3, cursor + 10);
    });
    cursor += 17;
  }
  return cursor;
}

function itemTable(doc: jsPDF, y: number, items: LineItem[]) {
  const columns = [14, 84, 112, 135, 166];
  const headers = ["Description / specification", "Qty.", "Unit", "Unit cost", "Amount"];
  doc.setFillColor(249, 241, 224);
  doc.rect(14, y, 182, 8, "F");
  headers.forEach((header, index) => { doc.setFont("helvetica", "bold"); doc.setFontSize(7); doc.setTextColor(123, 30, 30); doc.text(header, columns[index] + 2, y + 5); });
  let cursor = y + 8;
  items.forEach((item) => {
    const description = [item.description, item.specification].filter(Boolean).join(" — ");
    const descriptionLines = doc.splitTextToSize(description, 66);
    const height = Math.max(10, descriptionLines.length * 4 + 4);
    doc.setDrawColor(230, 226, 218);
    doc.rect(14, cursor, 182, height);
    [84, 112, 135, 166].forEach((x) => doc.line(x, cursor, x, cursor + height));
    doc.setFont("helvetica", "normal"); doc.setFontSize(8); doc.setTextColor(48, 57, 70);
    doc.text(descriptionLines, 16, cursor + 5);
    doc.text(String(item.quantity), 86, cursor + 5);
    doc.text(item.unit, 114, cursor + 5);
    doc.text(money(Number(item.amount) / Math.max(Number(item.quantity), 1)), 137, cursor + 5);
    doc.text(money(item.amount), 168, cursor + 5);
    cursor += height;
  });
  return cursor;
}

function footer(doc: jsPDF) {
  doc.setDrawColor(225, 220, 210); doc.line(14, 282, 196, 282);
  doc.setFont("helvetica", "normal"); doc.setFontSize(7); doc.setTextColor(105, 113, 126);
  doc.text(`Generated by ProcureWise on ${new Date().toLocaleString("en-PH")}. This offline copy reflects the recorded system data.`, 14, 287);
}

export function downloadPurchaseRequestPdf(input: { purchaseRequest: { prNumber: string; entityName: string; purpose: string; fundSource: string | null; fundCluster: string; responsibilityCenterCode: string | null; requesterDesignation: string | null; totalEstimate: string; createdAt: Date }; items: Array<{ description: string; specification: string | null; quantity: string; unit: string; estimatedUnitCost: string; totalCost: string }> }) {
  const { doc, y } = createDocument("PURCHASE REQUEST", "Appendix 60 · Purchase Request");
  let cursor = fields(doc, y, [{ label: "PR number", value: input.purchaseRequest.prNumber }, { label: "Entity", value: input.purchaseRequest.entityName }, { label: "Fund cluster", value: input.purchaseRequest.fundCluster }, { label: "Fund source", value: input.purchaseRequest.fundSource }, { label: "Responsibility center", value: input.purchaseRequest.responsibilityCenterCode }, { label: "Requested date", value: date(input.purchaseRequest.createdAt) }, { label: "Purpose", value: input.purchaseRequest.purpose }, { label: "Requester designation", value: input.purchaseRequest.requesterDesignation }]);
  cursor += 4; cursor = itemTable(doc, cursor, input.items.map((item) => ({ description: item.description, specification: item.specification, quantity: item.quantity, unit: item.unit, amount: item.totalCost })));
  doc.setFont("helvetica", "bold"); doc.setFontSize(10); doc.setTextColor(123, 30, 30); doc.text(`TOTAL ESTIMATE: ${money(input.purchaseRequest.totalEstimate)}`, 132, Math.min(cursor + 9, 270));
  footer(doc); invokeOfficialPdfDownload(doc, officialFormFileName("purchase_request", input.purchaseRequest.prNumber));
}

export function downloadPreCanvassPdf(input: { preCanvass: { preCanvassNumber: string; approvedBudget: string | null; quotationDeadline: Date | null; deliveryPeriodDays: number | null; priceEvaluationMode: string | null; createdAt: Date }; quotes: Array<{ totalPrice: string; deliveryDays: number; isCompliant: number; quotationReference: string | null; supplierId: number }>; supplierNames: Map<number, string> }) {
  const { doc, y } = createDocument("PRE-CANVASS / RFQ", "Annex D with Annex E acknowledgement references");
  let cursor = fields(doc, y, [{ label: "Pre-Canvass number", value: input.preCanvass.preCanvassNumber }, { label: "Prepared date", value: date(input.preCanvass.createdAt) }, { label: "Approved budget ceiling", value: money(input.preCanvass.approvedBudget) }, { label: "Quotation deadline", value: date(input.preCanvass.quotationDeadline) }, { label: "Delivery period", value: input.preCanvass.deliveryPeriodDays ? `${input.preCanvass.deliveryPeriodDays} day(s)` : "—" }, { label: "Evaluation basis", value: input.preCanvass.priceEvaluationMode?.replaceAll("_", " ") }]);
  cursor += 4; doc.setFont("helvetica", "bold"); doc.setFontSize(9); doc.setTextColor(48, 57, 70); doc.text("Supplier quotation summary", 14, cursor); cursor += 4;
  cursor = itemTable(doc, cursor, input.quotes.map((quote) => ({ description: input.supplierNames.get(quote.supplierId) || `Supplier #${quote.supplierId}`, specification: `${quote.isCompliant ? "Compliant" : "Non-compliant"} · Ref: ${quote.quotationReference || "—"}`, quantity: "1", unit: `${quote.deliveryDays} days`, amount: quote.totalPrice })));
  footer(doc); invokeOfficialPdfDownload(doc, officialFormFileName("pre_canvass", input.preCanvass.preCanvassNumber));
}

export function downloadAbstractPdf(input: { abstract: { abstractNumber: string; openingDate: Date; openingLocation: string; procurementCategory: string; recommendationReason: string; status: string; recommendedSupplierId: number }; supplierName?: string }) {
  const { doc, y } = createDocument("ABSTRACT OF CANVASS", "Annex F · Abstract of Quotation");
  const cursor = fields(doc, y, [{ label: "Abstract number", value: input.abstract.abstractNumber }, { label: "Status", value: input.abstract.status.toUpperCase() }, { label: "Opening date", value: date(input.abstract.openingDate) }, { label: "Opening location", value: input.abstract.openingLocation }, { label: "Procurement category", value: input.abstract.procurementCategory }, { label: "Recommended supplier", value: input.supplierName || `Supplier #${input.abstract.recommendedSupplierId}` }, { label: "Recommendation", value: input.abstract.recommendationReason }]);
  doc.setFont("helvetica", "italic"); doc.setFontSize(9); doc.setTextColor(105, 113, 126); doc.text("The recommendation is based on the recorded compliant quotation comparison.", 14, Math.min(cursor + 10, 272));
  footer(doc); invokeOfficialPdfDownload(doc, officialFormFileName("abstract", input.abstract.abstractNumber));
}

export function downloadPurchaseOrderPdf(input: { purchaseOrder: { poNumber: string; totalAmount: string; status: string; placeOfDelivery: string | null; scheduledDeliveryDate: Date | null; deliveryTerm: string | null; paymentTerm: string | null; modeOfProcurement: string | null; fundCluster: string | null; orsBursNumber: string | null; fundsAvailable: string | null; authorizedOfficialName: string | null; authorizedOfficialDesignation: string | null; chiefAccountantName: string | null }; supplierName?: string; supplierTin?: string | null }) {
  const { doc, y } = createDocument("PURCHASE ORDER", "Appendix 61 · Purchase Order");
  const cursor = fields(doc, y, [{ label: "PO number", value: input.purchaseOrder.poNumber }, { label: "Status", value: input.purchaseOrder.status.toUpperCase() }, { label: "Supplier", value: input.supplierName || "—" }, { label: "Supplier TIN", value: input.supplierTin }, { label: "Total amount", value: money(input.purchaseOrder.totalAmount) }, { label: "Fund cluster", value: input.purchaseOrder.fundCluster }, { label: "Place of delivery", value: input.purchaseOrder.placeOfDelivery }, { label: "Scheduled delivery", value: date(input.purchaseOrder.scheduledDeliveryDate) }, { label: "Delivery term", value: input.purchaseOrder.deliveryTerm }, { label: "Payment term", value: input.purchaseOrder.paymentTerm }, { label: "Mode of procurement", value: input.purchaseOrder.modeOfProcurement }, { label: "ORS/BURS", value: input.purchaseOrder.orsBursNumber }, { label: "Funds available", value: money(input.purchaseOrder.fundsAvailable) }, { label: "Authorised official", value: [input.purchaseOrder.authorizedOfficialName, input.purchaseOrder.authorizedOfficialDesignation].filter(Boolean).join(", ") }, { label: "Chief Accountant", value: input.purchaseOrder.chiefAccountantName }]);
  doc.setFont("helvetica", "italic"); doc.setFontSize(8); doc.setTextColor(105, 113, 126); doc.text("This downloadable copy is for offline reference and must be reconciled with the authorised procurement record.", 14, Math.min(cursor + 10, 272));
  footer(doc); invokeOfficialPdfDownload(doc, officialFormFileName("purchase_order", input.purchaseOrder.poNumber));
}
