import { EmptyWorkspace } from "@/components/EmptyWorkspace";
import { useAuth } from "@/_core/hooks/useAuth";
import { PageHeader } from "@/components/PageHeader";
import { RecordTable, RecordTableHeader } from "@/components/RecordTable";
import { StatusBadge } from "@/components/StatusBadge";
import { FormShell } from "@/components/FormShell";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { trpc } from "@/lib/trpc";
import { normalizeProcurementRole } from "../../../shared/procurementRules";
import { BarChart3, FileCheck2, FileSearch, LoaderCircle, Plus, ScrollText, UsersRound } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";

function formatMoney(value: number | string) { return `₱${Number(value).toLocaleString("en-PH", { minimumFractionDigits: 2 })}`; }

export function SupplierRegistryPage() {
  const [creating, setCreating] = useState(false);
  const utils = trpc.useUtils();
  const setup = trpc.procurement.setup.details.useQuery(undefined, { retry: false });
  const createSupplier = trpc.procurement.setup.createSupplier.useMutation({ onSuccess: () => { toast.success("Supplier registered."); setCreating(false); void utils.procurement.setup.details.invalidate(); }, onError: (error) => toast.error(error.message) });
  return <div className="mx-auto max-w-[1240px]"><PageHeader eyebrow="Vendor registry" title="Accredited suppliers" description="Maintain supplier contact information, accreditation status, and declared product or service offerings." action={{ label: "Register supplier", onClick: () => setCreating(!creating) }} />
    {creating && <SupplierForm isSaving={createSupplier.isPending} onCancel={() => setCreating(false)} onCreate={(input) => createSupplier.mutate(input)} />}
    <div className="mt-7">{setup.isLoading ? <LoadingPanel label="Loading supplier registry" /> : setup.data?.suppliers.length ? <RecordTable><RecordTableHeader><tr><th className="px-4 py-3 font-semibold">Supplier</th><th className="px-4 py-3 font-semibold">Contact</th><th className="px-4 py-3 font-semibold">Offerings</th><th className="px-4 py-3 font-semibold">Accreditation</th></tr></RecordTableHeader><tbody className="divide-y divide-[#efebe4]">{setup.data.suppliers.map((supplier) => <tr key={supplier.id}><td className="px-4 py-3"><p className="font-semibold text-[#3e4855]">{supplier.companyName}</p><p className="mt-0.5 text-[11px] text-[#7a8490]">{supplier.supplierCode}</p></td><td className="px-4 py-3 text-[#65717e]"><p>{supplier.contactPerson || "—"}</p><p className="mt-0.5 text-[11px]">{supplier.email || supplier.phone || "No contact details"}</p></td><td className="max-w-xs px-4 py-3 text-[#65717e]">{supplier.offerings || "—"}</td><td className="px-4 py-3"><StatusBadge tone={supplier.accreditationStatus === "accredited" ? "approved" : supplier.accreditationStatus === "suspended" ? "returned" : "pending"}>{supplier.accreditationStatus.toUpperCase()}</StatusBadge></td></tr>)}</tbody></RecordTable> : <EmptyWorkspace eyebrow="Vendor registry" title="No supplier records have been registered." description="Register an accredited supplier before selecting them for canvassing or quotation comparison." />}</div>
  </div>;
}

function SupplierForm({ isSaving, onCancel, onCreate }: { isSaving: boolean; onCancel: () => void; onCreate: (input: { supplierCode: string; companyName: string; contactPerson?: string; email?: string; phone?: string; address?: string; offerings?: string; accreditationStatus: "pending" | "accredited" | "suspended" }) => void }) {
  const [values, setValues] = useState({ supplierCode: "", companyName: "", contactPerson: "", email: "", phone: "", address: "", offerings: "", accreditationStatus: "pending" as const });
  const update = (field: keyof typeof values, value: string) => setValues((current) => ({ ...current, [field]: value }));
  return <form className="flat-panel mt-7 p-5 sm:p-6" onSubmit={(event) => { event.preventDefault(); if (!values.supplierCode.trim() || !values.companyName.trim()) return toast.error("Supplier code and company name are required."); onCreate({ ...values, supplierCode: values.supplierCode.trim(), companyName: values.companyName.trim(), contactPerson: values.contactPerson.trim() || undefined, email: values.email.trim() || undefined, phone: values.phone.trim() || undefined, address: values.address.trim() || undefined, offerings: values.offerings.trim() || undefined }); }}><div className="flex items-center justify-between border-b border-[#ece8df] pb-4"><div><p className="text-sm font-semibold text-[#34404e]">Supplier registration</p><p className="mt-1 text-[11px] text-[#77818d]">Supplier selection remains subject to canvass and compliance controls.</p></div><UsersRound className="h-4 w-4 text-[#7b1e1e]" /></div><div className="mt-6 grid gap-5 sm:grid-cols-2 lg:grid-cols-3"><Field label="Supplier code"><Input value={values.supplierCode} onChange={(event) => update("supplierCode", event.target.value)} placeholder="SUP-001" /></Field><Field label="Company name"><Input value={values.companyName} onChange={(event) => update("companyName", event.target.value)} placeholder="Registered legal name" /></Field><Field label="Accreditation"><Select value={values.accreditationStatus} onValueChange={(value) => update("accreditationStatus", value)}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="pending">Pending</SelectItem><SelectItem value="accredited">Accredited</SelectItem><SelectItem value="suspended">Suspended</SelectItem></SelectContent></Select></Field><Field label="Contact person"><Input value={values.contactPerson} onChange={(event) => update("contactPerson", event.target.value)} placeholder="Name" /></Field><Field label="Email"><Input value={values.email} onChange={(event) => update("email", event.target.value)} placeholder="email@example.com" /></Field><Field label="Phone"><Input value={values.phone} onChange={(event) => update("phone", event.target.value)} placeholder="Contact number" /></Field><div className="sm:col-span-2"><Field label="Product or service offerings"><Input value={values.offerings} onChange={(event) => update("offerings", event.target.value)} placeholder="Declared goods or services" /></Field></div><Field label="Address"><Input value={values.address} onChange={(event) => update("address", event.target.value)} placeholder="Business address" /></Field></div><div className="mt-6 flex justify-end gap-2"><Button type="button" variant="outline" onClick={onCancel} className="h-9 rounded-[4px] text-xs">Cancel</Button><Button disabled={isSaving} className="h-9 rounded-[4px] bg-[#7b1e1e] text-xs hover:bg-[#641818]">{isSaving && <LoaderCircle className="mr-1.5 h-3.5 w-3.5 animate-spin" />}Save supplier</Button></div></form>;
}

export function PlansPage() {
  const [creating, setCreating] = useState(false);
  const dashboard = trpc.procurement.dashboard.useQuery(undefined, { retry: false });
  const setup = trpc.procurement.setup.details.useQuery(undefined, { retry: false });
  const utils = trpc.useUtils();
  const createPlan = trpc.procurement.setup.createAppPpmpEntry.useMutation({ onSuccess: () => { toast.success("APP/PPMP entry added."); setCreating(false); void utils.procurement.dashboard.invalidate(); }, onError: (error) => toast.error(error.message) });
  return <div className="mx-auto max-w-[1240px]"><PageHeader eyebrow="Annual planning" title="APP / PPMP monitoring" description="Manage annual procurement plan and department PPMP entries, then monitor actual procurement against approved plans." action={{ label: "Add planning entry", onClick: () => setCreating(!creating) }} />{creating && <PlanForm setup={setup.data} isSaving={createPlan.isPending} onCancel={() => setCreating(false)} onCreate={(input) => createPlan.mutate(input)} />}<div className="mt-7">{dashboard.isLoading ? <LoadingPanel label="Loading APP/PPMP entries" /> : dashboard.data?.appPpmpEntries.length ? <RecordTable><RecordTableHeader><tr><th className="px-4 py-3 font-semibold">Fiscal year</th><th className="px-4 py-3 font-semibold">Description</th><th className="px-4 py-3 font-semibold">Planned</th><th className="px-4 py-3 font-semibold">Actual</th><th className="px-4 py-3 font-semibold">Status</th></tr></RecordTableHeader><tbody className="divide-y divide-[#efebe4]">{dashboard.data.appPpmpEntries.map((entry) => <tr key={entry.id}><td className="px-4 py-3 text-[#3e4855]">FY {entry.fiscalYear}</td><td className="px-4 py-3 font-medium text-[#3e4855]">{entry.description}</td><td className="px-4 py-3 text-[#3e4855]">{formatMoney(entry.plannedAmount)}</td><td className="px-4 py-3 text-[#3e4855]">{formatMoney(entry.actualAmount)}</td><td className="px-4 py-3"><StatusBadge tone={entry.status === "approved" ? "approved" : "draft"}>{entry.status.toUpperCase()}</StatusBadge></td></tr>)}</tbody></RecordTable> : <EmptyWorkspace eyebrow="Annual planning" title="No APP or PPMP entries have been registered." description="Add department-specific planned procurement entries to begin monitoring plan-versus-actual progress." />}</div></div>;
}

function PlanForm({ setup, isSaving, onCancel, onCreate }: { setup?: { offices: Array<{ id: number; code: string; name: string }>; objectsOfExpenditure: Array<{ id: number; code: string; name: string }> }; isSaving: boolean; onCancel: () => void; onCreate: (input: { fiscalYear: number; officeId: number; objectOfExpenditureId: number; description: string; plannedAmount: number }) => void }) {
  const [officeId, setOfficeId] = useState(""); const [objectId, setObjectId] = useState(""); const [description, setDescription] = useState(""); const [plannedAmount, setPlannedAmount] = useState(""); const year = new Date().getFullYear();
  return <FormShell title="APP / PPMP entry" description="Plan department procurement at the office and object-of-expenditure level." className="mt-7" onSubmit={(event) => { event.preventDefault(); if (!officeId || !objectId || !description.trim() || Number(plannedAmount) <= 0) return toast.error("Complete every planning field."); onCreate({ fiscalYear: year, officeId: Number(officeId), objectOfExpenditureId: Number(objectId), description: description.trim(), plannedAmount: Number(plannedAmount) }); }}><div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-4"><Field label={`Fiscal year`}><Input value={String(year)} readOnly /></Field><Field label="Office"><Select value={officeId} onValueChange={setOfficeId}><SelectTrigger><SelectValue placeholder="Select office" /></SelectTrigger><SelectContent>{setup?.offices.map((office) => <SelectItem key={office.id} value={String(office.id)}>{office.code} — {office.name}</SelectItem>)}</SelectContent></Select></Field><Field label="Object of expenditure"><Select value={objectId} onValueChange={setObjectId}><SelectTrigger><SelectValue placeholder="Select object" /></SelectTrigger><SelectContent>{setup?.objectsOfExpenditure.map((object) => <SelectItem key={object.id} value={String(object.id)}>{object.code} — {object.name}</SelectItem>)}</SelectContent></Select></Field><Field label="Planned amount"><Input type="number" min="0.01" step="0.01" value={plannedAmount} onChange={(event) => setPlannedAmount(event.target.value)} placeholder="0.00" /></Field><div className="sm:col-span-2 lg:col-span-4"><Field label="Planned procurement description"><Textarea value={description} onChange={(event) => setDescription(event.target.value)} placeholder="Describe the planned procurement." className="min-h-20" /></Field></div></div><div className="mt-6 flex justify-end gap-2"><Button type="button" variant="outline" onClick={onCancel} className="h-9 rounded-[4px] text-xs">Cancel</Button><Button disabled={isSaving} className="h-9 rounded-[4px] bg-[#7b1e1e] text-xs hover:bg-[#641818]">{isSaving && <LoaderCircle className="mr-1.5 h-3.5 w-3.5 animate-spin" />}Save plan entry</Button></div></FormShell>;
}

export function RfqPage() {
  const { user } = useAuth();
  const role = user ? normalizeProcurementRole(user.role) : "end_user";
  const canSupply = role === "supply_officer" || role === "admin";
  const [mode, setMode] = useState<"rfq" | "quotation" | null>(null);
  const dashboard = trpc.procurement.dashboard.useQuery(undefined, { retry: false });
  const setup = trpc.procurement.setup.details.useQuery(undefined, { retry: false });
  const utils = trpc.useUtils();
  const refresh = () => { void utils.procurement.dashboard.invalidate(); };
  const createRfq = trpc.procurement.rfqs.createFromPurchaseRequest.useMutation({ onSuccess: () => { toast.success("RFQ created for canvassing."); setMode(null); refresh(); }, onError: (error) => toast.error(error.message) });
  const addQuotation = trpc.procurement.rfqs.addQuotation.useMutation({ onSuccess: () => { toast.success("Supplier quotation recorded."); setMode(null); refresh(); }, onError: (error) => toast.error(error.message) });
  const generateAbstract = trpc.procurement.rfqs.generateAbstract.useMutation({ onSuccess: () => { toast.success("Abstract of Quotation generated."); refresh(); }, onError: (error) => toast.error(error.message) });
  const approvedPrs = dashboard.data?.purchaseRequests.filter((pr) => pr.status === "approved") ?? [];
  const quoteCount = (rfqId: number) => dashboard.data?.supplierQuotations.filter((quote) => quote.rfqId === rfqId).length ?? 0;
  const supplierMap = new Map((setup.data?.suppliers ?? []).map((supplier) => [supplier.id, supplier]));
  return <div className="mx-auto max-w-[1240px]"><PageHeader eyebrow="Quotation management" title="RFQs & quotation canvass" description="Create RFQs from approved PRs, record supplier quotations, and generate an abstract only after the mandatory three-supplier canvass." action={canSupply ? { label: "New RFQ", onClick: () => setMode(mode === "rfq" ? null : "rfq") } : undefined} />
    {mode === "rfq" && <form className="flat-panel mt-7 p-5" onSubmit={(event) => { event.preventDefault(); const value = new FormData(event.currentTarget).get("purchaseRequestId"); if (!value) return toast.error("Select an approved Purchase Request."); createRfq.mutate({ purchaseRequestId: Number(value) }); }}><p className="text-sm font-semibold text-[#34404e]">Create RFQ from approved PR</p><div className="mt-4 flex flex-col gap-3 sm:flex-row sm:items-end"><div className="w-full sm:max-w-md"><Label className="text-[11px] font-semibold">Approved Purchase Request</Label><Select name="purchaseRequestId"><SelectTrigger className="mt-1.5 h-9"><SelectValue placeholder="Select approved PR" /></SelectTrigger><SelectContent>{approvedPrs.map((pr) => <SelectItem key={pr.id} value={String(pr.id)}>{pr.prNumber} — {pr.purpose}</SelectItem>)}</SelectContent></Select></div><Button disabled={createRfq.isPending || !approvedPrs.length} className="h-9 rounded-[4px] bg-[#7b1e1e] text-xs hover:bg-[#641818]">{createRfq.isPending && <LoaderCircle className="mr-1.5 h-3.5 w-3.5 animate-spin" />}Start canvass</Button></div></form>}
    {mode === "quotation" && <QuotationForm rfqs={dashboard.data?.rfqs ?? []} suppliers={setup.data?.suppliers ?? []} isSaving={addQuotation.isPending} onCancel={() => setMode(null)} onCreate={(input) => addQuotation.mutate(input)} />}
    <div className="mt-7">{dashboard.isLoading ? <LoadingPanel label="Loading RFQ records" /> : dashboard.data?.rfqs.length ? <RecordTable><RecordTableHeader><tr><th className="px-4 py-3 font-semibold">RFQ</th><th className="px-4 py-3 font-semibold">Linked PR</th><th className="px-4 py-3 font-semibold">Quotations</th><th className="px-4 py-3 font-semibold">Status</th><th className="px-4 py-3 font-semibold">Action</th></tr></RecordTableHeader><tbody className="divide-y divide-[#efebe4]">{dashboard.data.rfqs.map((rfq) => { const quotations = quoteCount(rfq.id); const hasAbstract = dashboard.data.quotationAbstracts.some((abstract) => abstract.rfqId === rfq.id); return <tr key={rfq.id}><td className="px-4 py-3 font-semibold text-[#7b1e1e]">{rfq.rfqNumber}</td><td className="px-4 py-3 text-[#65717e]">PR #{rfq.purchaseRequestId}</td><td className="px-4 py-3"><StatusBadge tone={quotations >= 3 ? "approved" : "pending"}>{quotations}/3 SUPPLIERS</StatusBadge></td><td className="px-4 py-3"><StatusBadge tone={rfq.status === "approved" ? "approved" : "pending"}>{rfq.status.toUpperCase()}</StatusBadge></td><td className="px-4 py-3">{canSupply && !hasAbstract ? <div className="flex gap-2"><Button size="sm" variant="outline" onClick={() => setMode("quotation")} className="h-7 rounded-[4px] text-[10px]">Add quotation</Button><Button size="sm" disabled={quotations < 3 || generateAbstract.isPending} onClick={() => generateAbstract.mutate({ rfqId: rfq.id })} className="h-7 rounded-[4px] bg-[#7b1e1e] px-2 text-[10px] hover:bg-[#641818]">Abstract</Button></div> : <span className="text-[11px] text-[#7b8490]">{hasAbstract ? "Abstracted" : "Role-gated"}</span>}</td></tr>; })}</tbody></RecordTable> : <EmptyWorkspace eyebrow="Quotation management" title="No RFQ records are available for your role." description="A Supply Officer can convert an approved PR to an RFQ, then record the mandatory supplier quotations." />}</div>
    {dashboard.data?.rfqs.length ? <QuotationComparison rfqs={dashboard.data.rfqs} quotations={dashboard.data.supplierQuotations} supplierMap={supplierMap} /> : null}
    {canSupply && dashboard.data?.rfqs.length ? <Button variant="outline" onClick={() => setMode("quotation")} className="mt-4 h-9 rounded-[4px] text-xs"><Plus className="mr-1.5 h-3.5 w-3.5" />Record supplier quotation</Button> : null}
  </div>;
}

function QuotationForm({ rfqs, suppliers, isSaving, onCancel, onCreate }: { rfqs: Array<{ id: number; rfqNumber: string }>; suppliers: Array<{ id: number; supplierCode: string; companyName: string }>; isSaving: boolean; onCancel: () => void; onCreate: (input: { rfqId: number; supplierId: number; totalPrice: number; deliveryDays: number; isCompliant: boolean; notes?: string }) => void }) {
  const [rfqId, setRfqId] = useState(""); const [supplierId, setSupplierId] = useState(""); const [totalPrice, setTotalPrice] = useState(""); const [deliveryDays, setDeliveryDays] = useState(""); const [isCompliant, setIsCompliant] = useState("yes"); const [notes, setNotes] = useState("");
  return <FormShell title="Supplier quotation" description="Each supplier may provide one quotation per RFQ." icon={<FileSearch className="h-4 w-4" />} className="mt-7" onSubmit={(event) => { event.preventDefault(); if (!rfqId || !supplierId || Number(totalPrice) <= 0 || Number(deliveryDays) < 0) return toast.error("Complete the RFQ, supplier, price, and delivery fields."); onCreate({ rfqId: Number(rfqId), supplierId: Number(supplierId), totalPrice: Number(totalPrice), deliveryDays: Number(deliveryDays), isCompliant: isCompliant === "yes", notes: notes.trim() || undefined }); }}><div className="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-3"><Field label="RFQ"><Select value={rfqId} onValueChange={setRfqId}><SelectTrigger><SelectValue placeholder="Select RFQ" /></SelectTrigger><SelectContent>{rfqs.map((rfq) => <SelectItem key={rfq.id} value={String(rfq.id)}>{rfq.rfqNumber}</SelectItem>)}</SelectContent></Select></Field><Field label="Supplier"><Select value={supplierId} onValueChange={setSupplierId}><SelectTrigger><SelectValue placeholder="Select supplier" /></SelectTrigger><SelectContent>{suppliers.map((supplier) => <SelectItem key={supplier.id} value={String(supplier.id)}>{supplier.supplierCode} — {supplier.companyName}</SelectItem>)}</SelectContent></Select></Field><Field label="Total quotation"><Input type="number" min="0.01" step="0.01" value={totalPrice} onChange={(event) => setTotalPrice(event.target.value)} placeholder="0.00" /></Field><Field label="Delivery days"><Input type="number" min="0" value={deliveryDays} onChange={(event) => setDeliveryDays(event.target.value)} placeholder="0" /></Field><Field label="Compliance"><Select value={isCompliant} onValueChange={setIsCompliant}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="yes">Compliant</SelectItem><SelectItem value="no">Non-compliant</SelectItem></SelectContent></Select></Field><Field label="Notes"><Input value={notes} onChange={(event) => setNotes(event.target.value)} placeholder="Optional notes" /></Field></div><div className="mt-5 flex justify-end gap-2"><Button type="button" variant="outline" onClick={onCancel} className="h-9 rounded-[4px] text-xs">Cancel</Button><Button disabled={isSaving || !rfqs.length || !suppliers.length} className="h-9 rounded-[4px] bg-[#7b1e1e] text-xs hover:bg-[#641818]">{isSaving && <LoaderCircle className="mr-1.5 h-3.5 w-3.5 animate-spin" />}Save quotation</Button></div></FormShell>;
}

function QuotationComparison({ rfqs, quotations, supplierMap }: { rfqs: Array<{ id: number; rfqNumber: string }>; quotations: Array<{ id: number; rfqId: number; supplierId: number; totalPrice: string; deliveryDays: number; isCompliant: number }>; supplierMap: Map<number, { supplierCode: string; companyName: string }> }) {
  return <div className="flat-panel mt-6"><div className="border-b border-[#ece8df] px-5 py-4"><p className="text-sm font-semibold text-[#34404e]">Quotation comparison</p><p className="mt-1 text-[11px] text-[#77818d]">The lowest compliant quotation is visibly identified for each RFQ.</p></div>{rfqs.map((rfq) => { const rows = quotations.filter((quote) => quote.rfqId === rfq.id); const lowest = rows.filter((quote) => quote.isCompliant === 1).sort((a, b) => Number(a.totalPrice) - Number(b.totalPrice))[0]; return <div key={rfq.id} className="border-b border-[#efebe4] last:border-b-0"><div className="px-5 py-3 text-xs font-semibold text-[#7b1e1e]">{rfq.rfqNumber}</div>{rows.length ? <RecordTable className="border-x-0 border-b-0"><RecordTableHeader><tr><th className="px-4 py-3 font-semibold">Supplier</th><th className="px-4 py-3 font-semibold">Quoted total</th><th className="px-4 py-3 font-semibold">Delivery</th><th className="px-4 py-3 font-semibold">Compliance</th><th className="px-4 py-3 font-semibold">Recommendation</th></tr></RecordTableHeader><tbody className="divide-y divide-[#efebe4]">{rows.map((quote) => <tr key={quote.id} className={lowest?.id === quote.id ? "bg-[#fffaf0]" : ""}><td className="px-4 py-3 text-[#3e4855]">{supplierMap.get(quote.supplierId)?.companyName || `Supplier #${quote.supplierId}`}</td><td className="px-4 py-3 font-medium text-[#3e4855]">{formatMoney(quote.totalPrice)}</td><td className="px-4 py-3 text-[#65717e]">{quote.deliveryDays} day(s)</td><td className="px-4 py-3"><StatusBadge tone={quote.isCompliant ? "approved" : "returned"}>{quote.isCompliant ? "COMPLIANT" : "NON-COMPLIANT"}</StatusBadge></td><td className="px-4 py-3">{lowest?.id === quote.id ? <StatusBadge tone="pending">LOWEST COMPLIANT</StatusBadge> : "—"}</td></tr>)}</tbody></RecordTable> : <p className="px-5 pb-4 text-[11px] text-[#77818d]">No supplier quotations recorded.</p>}</div>; })}</div>;
}

export function PurchaseOrderPage() {
  const { user } = useAuth(); const role = user ? normalizeProcurementRole(user.role) : "end_user"; const canBac = role === "bac" || role === "admin"; const canSupply = role === "supply_officer" || role === "admin";
  const dashboard = trpc.procurement.dashboard.useQuery(undefined, { retry: false }); const utils = trpc.useUtils(); const refresh = () => { void utils.procurement.dashboard.invalidate(); };
  const approve = trpc.procurement.rfqs.approveAbstract.useMutation({ onSuccess: () => { toast.success("Quotation abstract approved by BAC."); refresh(); }, onError: (error) => toast.error(error.message) });
  const createPo = trpc.procurement.rfqs.createPurchaseOrder.useMutation({ onSuccess: () => { toast.success("Purchase Order generated."); refresh(); }, onError: (error) => toast.error(error.message) });
  return <div className="mx-auto max-w-[1240px]"><PageHeader eyebrow="Purchase execution" title="Abstracts & Purchase Orders" description="Review quotation abstracts and create a Purchase Order only after BAC approval of the recommended compliant supplier." /><div className="mt-7 grid gap-6 xl:grid-cols-2"><div className="flat-panel"><div className="border-b border-[#ece8df] px-5 py-4"><p className="text-sm font-semibold text-[#34404e]">Abstracts of Quotation</p><p className="mt-1 text-[11px] text-[#77818d]">Lowest compliant quote is proposed after the three-supplier canvass.</p></div>{dashboard.data?.quotationAbstracts.length ? <div className="divide-y divide-[#efebe4]">{dashboard.data.quotationAbstracts.map((abstract) => <div key={abstract.id} className="flex items-center justify-between gap-4 p-5"><div><p className="text-xs font-semibold text-[#3e4855]">RFQ #{abstract.rfqId}</p><p className="mt-1 text-[11px] text-[#72808c]">Supplier #{abstract.recommendedSupplierId}</p><StatusBadge tone={abstract.status === "approved" ? "approved" : "pending"}>{abstract.status.toUpperCase()}</StatusBadge></div><div className="flex gap-2">{canBac && abstract.status === "recommended" && <Button size="sm" onClick={() => approve.mutate({ rfqId: abstract.rfqId })} disabled={approve.isPending} className="h-7 rounded-[4px] bg-[#7b1e1e] text-[10px] hover:bg-[#641818]">BAC approve</Button>}{canSupply && abstract.status === "approved" && <Button size="sm" onClick={() => createPo.mutate({ rfqId: abstract.rfqId })} disabled={createPo.isPending} className="h-7 rounded-[4px] bg-[#7b1e1e] text-[10px] hover:bg-[#641818]">Generate PO</Button>}</div></div>)}</div> : <div className="p-8 text-center text-[11px] leading-5 text-[#72808c]">No abstracts are ready for review. Complete an RFQ canvass with at least three supplier quotations.</div>}</div><div className="flat-panel"><div className="border-b border-[#ece8df] px-5 py-4"><p className="text-sm font-semibold text-[#34404e]">Purchase Orders</p><p className="mt-1 text-[11px] text-[#77818d]">Generated POs remain traceable to their RFQ and linked Purchase Request.</p></div>{dashboard.data?.purchaseOrders.length ? <div className="divide-y divide-[#efebe4]">{dashboard.data.purchaseOrders.map((po) => <div key={po.id} className="flex items-center justify-between gap-4 p-5"><div><p className="text-xs font-semibold text-[#7b1e1e]">{po.poNumber}</p><p className="mt-1 text-[11px] text-[#72808c]">{formatMoney(po.totalAmount)} · Supplier #{po.supplierId}</p></div><StatusBadge tone={po.status === "approved" ? "approved" : "pending"}>{po.status.replaceAll("_", " ").toUpperCase()}</StatusBadge></div>)}</div> : <div className="p-8 text-center text-[11px] leading-5 text-[#72808c]">No Purchase Orders have been generated.</div>}</div></div></div>;
}

export function BudgetPage() {
  const budgets = trpc.procurement.setup.budgetUtilization.useQuery(undefined, { retry: false });
  return <div className="mx-auto max-w-[1240px]"><PageHeader eyebrow="Allotment control" title="Budget utilization" description="Track allotted, committed, and available balances at the specific office and object-of-expenditure level." /> <div className="mt-7">{budgets.isLoading ? <LoadingPanel label="Loading budget utilization" /> : budgets.data?.length ? <RecordTable><RecordTableHeader><tr><th className="px-4 py-3 font-semibold">Office</th><th className="px-4 py-3 font-semibold">Object of expenditure</th><th className="px-4 py-3 font-semibold">FY</th><th className="px-4 py-3 font-semibold">Allotted</th><th className="px-4 py-3 font-semibold">Committed</th><th className="px-4 py-3 font-semibold">Available</th></tr></RecordTableHeader><tbody className="divide-y divide-[#efebe4]">{budgets.data.map((budget) => <tr key={budget.id}><td className="px-4 py-3 text-[#3e4855]">{budget.office ? `${budget.office.code} — ${budget.office.name}` : `Office #${budget.officeId}`}</td><td className="px-4 py-3 text-[#3e4855]">{budget.objectOfExpenditure ? `${budget.objectOfExpenditure.code} — ${budget.objectOfExpenditure.name}` : `Object #${budget.objectOfExpenditureId}`}</td><td className="px-4 py-3 text-[#65717e]">{budget.fiscalYear}</td><td className="px-4 py-3 text-[#3e4855]">{formatMoney(budget.allottedAmount)}</td><td className="px-4 py-3 text-[#3e4855]">{formatMoney(budget.committedAmount)}</td><td className="px-4 py-3"><StatusBadge tone={Number(budget.availableAmount) > 0 ? "approved" : "returned"}>{formatMoney(budget.availableAmount)}</StatusBadge></td></tr>)}</tbody></RecordTable> : <EmptyWorkspace eyebrow="Allotment control" title="No office-level budget allotments have been registered." description="Use System setup to create an office, an object of expenditure, and the associated fiscal-year allotment before PR submissions can be validated." actionLabel="Open system setup" actionHref="/setup" />}</div></div>;
}

export function AnalyticsPage() {
  const dashboard = trpc.procurement.dashboard.useQuery(undefined, { retry: false });
  const data = dashboard.data;
  const planned = data?.appPpmpEntries.reduce((sum, entry) => sum + Number(entry.plannedAmount), 0) ?? 0;
  const actual = data?.appPpmpEntries.reduce((sum, entry) => sum + Number(entry.actualAmount), 0) ?? 0;
  const prEstimate = data?.purchaseRequests.reduce((sum, pr) => sum + Number(pr.totalEstimate), 0) ?? 0;
  const percentage = planned ? Math.min(100, (actual / planned) * 100) : 0;
  const cycleTime = data?.analytics.averageCycleTimeDays;
  const topCommodities = data?.analytics.topCommodities ?? [];
  return <div className="mx-auto max-w-[1240px]"><PageHeader eyebrow="Procurement intelligence" title="Analytics & performance" description="Live, record-backed measures for workflow volume, budget plan-versus-actual progress, closed-PO cycle time, and completed commodities." /><div className="mt-7 grid gap-4 md:grid-cols-3"><Metric label="Purchase Request estimate" value={formatMoney(prEstimate)} detail="Aggregate of PRs visible to your role." icon={BarChart3} /><Metric label="Planned APP / PPMP" value={formatMoney(planned)} detail="Aggregate value of registered plan entries." icon={FileCheck2} /><Metric label="Purchase Order volume" value={String(data?.purchaseOrders.length ?? 0)} detail="Purchase Orders generated from approved abstracts." icon={FileSearch} /></div><div className="flat-panel mt-6 p-6"><div className="flex items-start justify-between gap-5"><div><p className="text-sm font-semibold text-[#34404e]">Budget plan versus actual</p><p className="mt-1 text-[11px] text-[#77818d]">Actual spending becomes available as related procurement records are completed.</p></div><p className="font-display text-2xl font-semibold text-[#7b1e1e]">{planned ? `${percentage.toFixed(1)}%` : "—"}</p></div><div className="mt-6 h-3 overflow-hidden rounded-[3px] bg-[#eeeae1]"><div className="h-full bg-[#9a6d19] transition-[width] duration-300" style={{ width: `${percentage}%` }} /></div><div className="mt-3 flex justify-between text-[11px] text-[#737e8a]"><span>Planned: {formatMoney(planned)}</span><span>Actual: {formatMoney(actual)}</span></div></div><div className="mt-6 grid gap-4 lg:grid-cols-2"><div className="flat-panel p-5"><p className="text-sm font-semibold text-[#34404e]">Average procurement cycle time</p><p className="mt-3 font-display text-2xl font-semibold text-[#7b1e1e]">{cycleTime === null || cycleTime === undefined ? "—" : `${cycleTime.toFixed(1)} days`}</p><p className="mt-2 text-[11px] leading-5 text-[#72808c]">Calculated only from PR records linked to Purchase Orders in the explicit closed state.</p></div><div className="flat-panel p-5"><p className="text-sm font-semibold text-[#34404e]">Top commodities</p>{topCommodities.length ? <ol className="mt-3 divide-y divide-[#efebe4]">{topCommodities.map((commodity, index) => <li key={commodity.description} className="flex items-center justify-between gap-3 py-2 text-[11px]"><span className="text-[#3e4855]"><span className="mr-2 font-bold text-[#9a6d19]">{index + 1}.</span>{commodity.description}</span><span className="font-semibold text-[#7b1e1e]">{formatMoney(commodity.amount)}</span></li>)}</ol> : <p className="mt-2 text-[11px] leading-5 text-[#72808c]">No closed-PO commodity records are available yet.</p>}</div></div></div>;
}

export function AuditTrailPage() {
  const dashboard = trpc.procurement.dashboard.useQuery(undefined, { retry: false });
  return <div className="mx-auto max-w-[1240px]"><PageHeader eyebrow="Accountability" title="Audit trail" description="Time-stamped record of authorised configuration, workflow, approval, quotation, and Purchase Order actions." /> <div className="mt-7">{dashboard.isLoading ? <LoadingPanel label="Loading audit trail" /> : dashboard.data?.auditEvents.length ? <RecordTable><RecordTableHeader><tr><th className="px-4 py-3 font-semibold">Timestamp</th><th className="px-4 py-3 font-semibold">Transaction</th><th className="px-4 py-3 font-semibold">Action</th><th className="px-4 py-3 font-semibold">Role</th></tr></RecordTableHeader><tbody className="divide-y divide-[#efebe4]">{dashboard.data.auditEvents.map((event) => <tr key={event.id}><td className="px-4 py-3 text-[#65717e]">{new Date(event.createdAt).toLocaleString("en-PH")}</td><td className="px-4 py-3 font-semibold text-[#3e4855]">{event.entityType.replaceAll("_", " ")}</td><td className="px-4 py-3 text-[#65717e]">{event.action.replaceAll("_", " ")}</td><td className="px-4 py-3"><StatusBadge tone="active">{event.performedByRole.replaceAll("_", " ").toUpperCase()}</StatusBadge></td></tr>)}</tbody></RecordTable> : <EmptyWorkspace eyebrow="Accountability" title="No audit events have been recorded." description="Every authorised configuration and procurement workflow action creates a time-stamped event here." />}</div></div>;
}

function Metric({ label, value, detail, icon: Icon }: { label: string; value: string; detail: string; icon: typeof BarChart3 }) { return <div className="flat-panel p-5"><div className="flex items-start justify-between"><div><p className="text-[10px] font-bold uppercase tracking-[0.12em] text-[#9a6d19]">{label}</p><p className="mt-4 font-display text-2xl font-semibold text-[#202833]">{value}</p></div><Icon className="h-4 w-4 text-[#7b1e1e]" /></div><p className="mt-3 text-[11px] leading-5 text-[#73808b]">{detail}</p></div>; }
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <div><Label className="text-[11px] font-semibold text-[#4c5664]">{label}</Label><div className="mt-1.5">{children}</div></div>; }
function LoadingPanel({ label }: { label: string }) { return <div className="flat-panel grid min-h-72 place-items-center text-center"><div><LoaderCircle className="mx-auto h-5 w-5 animate-spin text-[#7b1e1e]" /><p className="mt-3 text-xs text-[#6e7885]">{label}</p></div></div>; }
