import { Button } from "@/components/ui/button";
import { trpc } from "@/lib/trpc";
import { ArrowLeft, Printer } from "lucide-react";
import { useLocation, useSearch } from "wouter";

function PrintShell({ title, children }: { title: string; children: React.ReactNode }) {
  const [, setLocation] = useLocation();
  return <div className="mx-auto max-w-[900px] print:max-w-none"><div className="mb-6 flex items-center justify-between print:hidden"><Button variant="outline" onClick={() => setLocation("/dashboard")} className="rounded-[4px]"><ArrowLeft className="mr-1.5 h-4 w-4" />Back to workspace</Button><Button onClick={() => window.print()} className="rounded-[4px] bg-[#7b1e1e] hover:bg-[#641818]"><Printer className="mr-1.5 h-4 w-4" />Print</Button></div><article className="border border-[#d8d1c4] bg-white p-8 shadow-sm print:border-0 print:p-0 print:shadow-none"><header className="border-b-2 border-[#7b1e1e] pb-5 text-center"><p className="text-xs font-bold tracking-[0.18em] text-[#9a6d19]">BATANES STATE COLLEGE</p><h1 className="mt-2 font-display text-2xl font-semibold text-[#202833]">{title}</h1><p className="mt-1 text-[11px] text-[#65717e]">ProcureWise controlled offline copy</p></header>{children}</article></div>;
}
function useId(key: string) { return Number(new URLSearchParams(useSearch()).get(key)); }
function Loading() { return <p className="py-16 text-center text-sm text-[#77818d]">Loading printable record…</p>; }
function NotFound() { return <p className="py-16 text-center text-sm text-[#77818d]">The requested printable record is not available.</p>; }

export function PrintNoticePage() {
  const id = useId("id"); const notices = trpc.procurement.officer.notices.list.useQuery(undefined, { retry: false }); const notice = notices.data?.find((record) => record.id === id);
  return <PrintShell title="LETTER OF NOTICE">{notices.isLoading ? <Loading /> : !notice ? <NotFound /> : <div className="pt-7"><div className="grid gap-4 text-sm sm:grid-cols-2"><p><strong>Notice No.:</strong> {notice.noticeNumber}</p><p><strong>Date:</strong> {new Date(notice.createdAt).toLocaleDateString("en-PH")}</p><p><strong>Type:</strong> {notice.noticeType.replaceAll("_", " ")}</p><p><strong>Status:</strong> {notice.status.toUpperCase()}</p></div><h2 className="mt-8 text-base font-semibold text-[#7b1e1e]">{notice.subject}</h2><p className="mt-4 whitespace-pre-wrap text-sm leading-7 text-[#3f4a57]">{notice.body}</p><div className="mt-16 grid grid-cols-2 gap-12 text-center text-xs text-[#566171]"><div className="border-t border-[#9f998f] pt-2">Prepared / issued by</div><div className="border-t border-[#9f998f] pt-2">Received by</div></div></div>}</PrintShell>;
}

export function PrintTransmittalPage() {
  const id = useId("id"); const transmittals = trpc.procurement.officer.transmittals.list.useQuery(undefined, { retry: false }); const item = transmittals.data?.find((record) => record.id === id);
  return <PrintShell title="BAC TRANSMITTAL">{transmittals.isLoading ? <Loading /> : !item ? <NotFound /> : <div className="pt-7"><div className="grid gap-4 text-sm sm:grid-cols-2"><p><strong>Transmittal No.:</strong> {item.transmittalNumber}</p><p><strong>Date:</strong> {new Date(item.createdAt).toLocaleDateString("en-PH")}</p><p><strong>From:</strong> {item.fromOffice}</p><p><strong>To:</strong> {item.toOffice}</p><p><strong>Status:</strong> {item.status.toUpperCase()}</p><p><strong>Linked PR ID:</strong> {item.purchaseRequestId || "—"}</p></div><h2 className="mt-8 text-base font-semibold text-[#7b1e1e]">{item.subject}</h2><p className="mt-4 whitespace-pre-wrap text-sm leading-7 text-[#3f4a57]">{item.remarks || "No additional routing remarks recorded."}</p><div className="mt-16 grid grid-cols-2 gap-12 text-center text-xs text-[#566171]"><div className="border-t border-[#9f998f] pt-2">Prepared by</div><div className="border-t border-[#9f998f] pt-2">Received / acknowledged by</div></div></div>}</PrintShell>;
}

export function PrintPreCanvassAbstractPage() {
  const preCanvassId = useId("preCanvassId"); const dashboard = trpc.procurement.dashboard.useQuery(undefined, { retry: false }); const setup = trpc.procurement.setup.details.useQuery(undefined, { retry: false }); const abstract = dashboard.data?.abstractsOfCanvass.find((record) => record.preCanvassId === preCanvassId); const quotes = dashboard.data?.preCanvassQuotes.filter((quote) => quote.preCanvassId === preCanvassId) ?? [];
  return <PrintShell title="ABSTRACT OF CANVASS">{dashboard.isLoading ? <Loading /> : !abstract ? <NotFound /> : <div className="pt-7"><div className="grid gap-4 text-sm sm:grid-cols-2"><p><strong>Abstract No.:</strong> {abstract.abstractNumber}</p><p><strong>Status:</strong> {abstract.status.toUpperCase()}</p><p><strong>Opening date:</strong> {new Date(abstract.openingDate).toLocaleDateString("en-PH")}</p><p><strong>Opening location:</strong> {abstract.openingLocation}</p><p><strong>Category:</strong> {abstract.procurementCategory}</p><p><strong>Recommended supplier:</strong> {setup.data?.suppliers.find((supplier) => supplier.id === abstract.recommendedSupplierId)?.companyName || `Supplier #${abstract.recommendedSupplierId}`}</p></div><h2 className="mt-8 text-base font-semibold text-[#7b1e1e]">Quotation comparison</h2><table className="mt-3 w-full border-collapse text-xs"><thead><tr className="bg-[#f9f1e0] text-left text-[#7b1e1e]"><th className="border border-[#ddd6ca] p-2">Supplier</th><th className="border border-[#ddd6ca] p-2">Quoted price</th><th className="border border-[#ddd6ca] p-2">Delivery</th><th className="border border-[#ddd6ca] p-2">Compliance</th></tr></thead><tbody>{quotes.map((quote) => <tr key={quote.id}><td className="border border-[#ddd6ca] p-2">{setup.data?.suppliers.find((supplier) => supplier.id === quote.supplierId)?.companyName || `Supplier #${quote.supplierId}`}</td><td className="border border-[#ddd6ca] p-2">₱{Number(quote.totalPrice).toLocaleString("en-PH", { minimumFractionDigits: 2 })}</td><td className="border border-[#ddd6ca] p-2">{quote.deliveryDays} day(s)</td><td className="border border-[#ddd6ca] p-2">{quote.isCompliant ? "Compliant" : "Non-compliant"}</td></tr>)}</tbody></table><h2 className="mt-8 text-base font-semibold text-[#7b1e1e]">Recommendation</h2><p className="mt-3 text-sm leading-7 text-[#3f4a57]">{abstract.recommendationReason}</p><div className="mt-16 grid grid-cols-2 gap-12 text-center text-xs text-[#566171]"><div className="border-t border-[#9f998f] pt-2">Prepared by Procurement</div><div className="border-t border-[#9f998f] pt-2">Administrative decision</div></div></div>}</PrintShell>;
}
