import { PageHeader } from "@/components/PageHeader";
import { RecordTable, RecordTableHeader } from "@/components/RecordTable";
import { FormShell } from "@/components/FormShell";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { useAuth } from "@/_core/hooks/useAuth";
import { trpc } from "@/lib/trpc";
import { LoaderCircle, Settings2 } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";

const roleLabels = { end_user: "End-User", procurement_officer: "Procurement Officer", administrative_approver: "Administrative Approver", admin: "Admin" } as const;

export default function SetupPage() {
  const { user, loading: authLoading } = useAuth();
  const isAdmin = user?.role === "admin";
  const utils = trpc.useUtils();
  const setup = trpc.procurement.setup.details.useQuery(undefined, { retry: false });
  const users = trpc.procurement.setup.users.useQuery(undefined, { retry: false, enabled: Boolean(isAdmin) });
  const refresh = () => { void utils.procurement.setup.details.invalidate(); };
  const createOffice = trpc.procurement.setup.createOffice.useMutation({ onSuccess: () => { toast.success("Office added."); refresh(); }, onError: (error) => toast.error(error.message) });
  const createObject = trpc.procurement.setup.createObjectOfExpenditure.useMutation({ onSuccess: () => { toast.success("Object of expenditure added."); refresh(); }, onError: (error) => toast.error(error.message) });
  const createBudget = trpc.procurement.setup.createBudgetAllotment.useMutation({ onSuccess: () => { toast.success("Budget allotment recorded."); refresh(); }, onError: (error) => toast.error(error.message) });
  const updateUserRole = trpc.procurement.setup.updateUserRole.useMutation({ onSuccess: () => { toast.success("Workflow role updated."); void utils.procurement.setup.users.invalidate(); }, onError: (error) => toast.error(error.message) });
  const [officeCode, setOfficeCode] = useState("");
  const [officeName, setOfficeName] = useState("");
  const [objectCode, setObjectCode] = useState("");
  const [objectName, setObjectName] = useState("");
  const [budgetOffice, setBudgetOffice] = useState("");
  const [budgetObject, setBudgetObject] = useState("");
  const [budgetAmount, setBudgetAmount] = useState("");
  const currentYear = new Date().getFullYear();

  return <div className="mx-auto max-w-[1240px]"><PageHeader eyebrow="Administrative controls" title="System setup" description="Configure the office, expenditure, and allotment references that are mandatory before Purchase Requests may be budget-validated and routed." />
    <div className="mt-7 grid gap-5 xl:grid-cols-3">
      <form onSubmit={(event) => { event.preventDefault(); createOffice.mutate({ code: officeCode.trim(), name: officeName.trim() }); }} className="flat-panel p-5"><Settings2 className="h-4 w-4 text-[#7b1e1e]" /><h2 className="mt-4 text-sm font-semibold text-[#34404e]">Requesting offices</h2><p className="mt-1 text-[11px] leading-5 text-[#72808c]">Each PR is tied to a requesting office.</p><div className="mt-5 grid gap-3"><div><Label htmlFor="office-code" className="text-[11px] font-semibold">Office code</Label><Input id="office-code" value={officeCode} onChange={(event) => setOfficeCode(event.target.value)} placeholder="e.g., BSC-PROC" className="mt-1.5 h-9 text-xs" /></div><div><Label htmlFor="office-name" className="text-[11px] font-semibold">Office name</Label><Input id="office-name" value={officeName} onChange={(event) => setOfficeName(event.target.value)} placeholder="Office name" className="mt-1.5 h-9 text-xs" /></div><Button disabled={createOffice.isPending || !officeCode.trim() || !officeName.trim()} className="mt-1 h-9 rounded-[4px] bg-[#7b1e1e] text-xs hover:bg-[#641818]">{createOffice.isPending && <LoaderCircle className="mr-1.5 h-3.5 w-3.5 animate-spin" />}Add office</Button></div></form>
      <form onSubmit={(event) => { event.preventDefault(); createObject.mutate({ code: objectCode.trim(), name: objectName.trim() }); }} className="flat-panel p-5"><Settings2 className="h-4 w-4 text-[#7b1e1e]" /><h2 className="mt-4 text-sm font-semibold text-[#34404e]">Objects of expenditure</h2><p className="mt-1 text-[11px] leading-5 text-[#72808c]">Budget authority is controlled at this classification level.</p><div className="mt-5 grid gap-3"><div><Label htmlFor="object-code" className="text-[11px] font-semibold">Object code</Label><Input id="object-code" value={objectCode} onChange={(event) => setObjectCode(event.target.value)} placeholder="e.g., 50203010" className="mt-1.5 h-9 text-xs" /></div><div><Label htmlFor="object-name" className="text-[11px] font-semibold">Object name</Label><Input id="object-name" value={objectName} onChange={(event) => setObjectName(event.target.value)} placeholder="e.g., Office supplies" className="mt-1.5 h-9 text-xs" /></div><Button disabled={createObject.isPending || !objectCode.trim() || !objectName.trim()} className="mt-1 h-9 rounded-[4px] bg-[#7b1e1e] text-xs hover:bg-[#641818]">{createObject.isPending && <LoaderCircle className="mr-1.5 h-3.5 w-3.5 animate-spin" />}Add expenditure object</Button></div></form>
      <FormShell title="Office budget allotment" description="A PR can proceed only when its selected allotment has available funds." icon={<Settings2 className="h-4 w-4" />} onSubmit={(event) => { event.preventDefault(); createBudget.mutate({ officeId: Number(budgetOffice), objectOfExpenditureId: Number(budgetObject), fiscalYear: currentYear, allottedAmount: Number(budgetAmount) }); }}><div className="mt-5 grid gap-3"><div><Label className="text-[11px] font-semibold">Office</Label><Select value={budgetOffice} onValueChange={setBudgetOffice}><SelectTrigger className="mt-1.5 h-9 text-xs"><SelectValue placeholder="Select office" /></SelectTrigger><SelectContent>{setup.data?.offices.map((office) => <SelectItem key={office.id} value={String(office.id)}>{office.code} — {office.name}</SelectItem>)}</SelectContent></Select></div><div><Label className="text-[11px] font-semibold">Object of expenditure</Label><Select value={budgetObject} onValueChange={setBudgetObject}><SelectTrigger className="mt-1.5 h-9 text-xs"><SelectValue placeholder="Select object" /></SelectTrigger><SelectContent>{setup.data?.objectsOfExpenditure.map((object) => <SelectItem key={object.id} value={String(object.id)}>{object.code} — {object.name}</SelectItem>)}</SelectContent></Select></div><div><Label htmlFor="budget-amount" className="text-[11px] font-semibold">Allotted amount for FY {currentYear}</Label><Input id="budget-amount" type="number" min="0.01" step="0.01" value={budgetAmount} onChange={(event) => setBudgetAmount(event.target.value)} placeholder="0.00" className="mt-1.5 h-9 text-xs" /></div><Button disabled={createBudget.isPending || !budgetOffice || !budgetObject || Number(budgetAmount) <= 0} className="mt-1 h-9 rounded-[4px] bg-[#7b1e1e] text-xs hover:bg-[#641818]">{createBudget.isPending && <LoaderCircle className="mr-1.5 h-3.5 w-3.5 animate-spin" />}Record allotment</Button></div></FormShell>
    </div>
    <div className="mt-7 flat-panel"><div className="border-b border-[#ece8df] px-5 py-4"><p className="text-sm font-semibold text-[#34404e]">Current configuration</p><p className="mt-1 text-[11px] text-[#77818d]">Only active records are made available to transactional forms.</p></div><RecordTable className="border-0"><RecordTableHeader><tr><th className="px-4 py-3 font-semibold">Requesting offices</th><th className="px-4 py-3 font-semibold">Objects of expenditure</th><th className="px-4 py-3 font-semibold">Supplier registry</th></tr></RecordTableHeader><tbody><tr><td className="px-4 py-4 align-top text-[#596574]">{setup.data?.offices.length ? setup.data.offices.map((office) => <p key={office.id} className="mb-1.5">{office.code} — {office.name}</p>) : "No offices configured."}</td><td className="px-4 py-4 align-top text-[#596574]">{setup.data?.objectsOfExpenditure.length ? setup.data.objectsOfExpenditure.map((object) => <p key={object.id} className="mb-1.5">{object.code} — {object.name}</p>) : "No expenditure objects configured."}</td><td className="px-4 py-4 align-top text-[#596574]">{setup.data?.suppliers.length ? `${setup.data.suppliers.length} active supplier record(s)` : "No suppliers registered."}</td></tr></tbody></RecordTable></div>
    <div className="mt-7 flat-panel"><div className="border-b border-[#ece8df] px-5 py-4"><p className="text-sm font-semibold text-[#34404e]">User role assignment</p><p className="mt-1 text-[11px] text-[#77818d]">Assign one of the five procurement workflow roles to each authenticated account.</p></div>{authLoading ? <p className="px-5 py-7 text-center text-xs text-[#77818d]">Confirming administrator access…</p> : !isAdmin ? <p className="px-5 py-7 text-center text-xs text-[#77818d]">Only administrators can view or assign workflow roles.</p> : <RecordTable className="border-0"><RecordTableHeader><tr><th className="px-4 py-3 font-semibold">Account</th><th className="px-4 py-3 font-semibold">Email</th><th className="px-4 py-3 font-semibold">Workflow role</th><th className="px-4 py-3 font-semibold">Last sign-in</th></tr></RecordTableHeader><tbody className="divide-y divide-[#efebe4]">{users.isLoading ? <tr><td colSpan={4} className="px-4 py-7 text-center text-xs text-[#77818d]">Loading users…</td></tr> : users.data?.map((user) => <tr key={user.id}><td className="px-4 py-3 font-semibold text-[#3f4a57]">{user.name || "Unnamed account"}</td><td className="px-4 py-3 text-[#6d7884]">{user.email || "—"}</td><td className="px-4 py-2"><Select value={user.role === "user" ? "end_user" : user.role} onValueChange={(role) => updateUserRole.mutate({ userId: user.id, role: role as keyof typeof roleLabels })}><SelectTrigger className="h-8 w-44 rounded-[4px] text-xs"><SelectValue /></SelectTrigger><SelectContent>{Object.entries(roleLabels).map(([value, label]) => <SelectItem key={value} value={value}>{label}</SelectItem>)}</SelectContent></Select></td><td className="px-4 py-3 text-[#6d7884]">{new Date(user.lastSignedIn).toLocaleDateString("en-PH")}</td></tr>)}</tbody></RecordTable>}</div>
  </div>;
}
