import { useAuth } from "@/_core/hooks/useAuth";
import { EmptyWorkspace } from "@/components/EmptyWorkspace";
import { FormShell } from "@/components/FormShell";
import { PageHeader } from "@/components/PageHeader";
import { RecordTable, RecordTableHeader } from "@/components/RecordTable";
import { StatusBadge } from "@/components/StatusBadge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { trpc } from "@/lib/trpc";
import { normalizeProcurementRole } from "../../../shared/procurementRules";
import { CheckCircle2, ClipboardList, FileCheck2, FileSearch, LoaderCircle, PackageCheck, Plus } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";

const money = (value: number | string) => `₱${Number(value).toLocaleString("en-PH", { minimumFractionDigits: 2 })}`;
const tone = (status: string) => status === "approved" || status === "pmr_logged" || status === "closed" ? "approved" : status === "rejected" ? "returned" : status === "draft" ? "draft" : "pending";

export function PreCanvassPage() {
  const { user } = useAuth();
  const role = user ? normalizeProcurementRole(user.role) : "end_user";
  const isEndUser = role === "end_user" || role === "admin";
  const isProcurement = role === "procurement_officer" || role === "admin";
  const [mode, setMode] = useState<"create" | "quote" | null>(null);
  const dashboard = trpc.procurement.dashboard.useQuery(undefined, { retry: false });
  const setup = trpc.procurement.setup.details.useQuery(undefined, { retry: false });
  const utils = trpc.useUtils();
  const refresh = () => void utils.procurement.dashboard.invalidate();
  const create = trpc.procurement.preCanvasses.create.useMutation({ onSuccess: () => { toast.success("Pre-Canvass opened for supplier quotes."); setMode(null); refresh(); }, onError: (error) => toast.error(error.message) });
  const addQuote = trpc.procurement.preCanvasses.addQuote.useMutation({ onSuccess: () => { toast.success("Pre-Canvass supplier quote recorded."); setMode(null); refresh(); }, onError: (error) => toast.error(error.message) });
  const submit = trpc.procurement.preCanvasses.submit.useMutation({ onSuccess: () => { toast.success("Pre-Canvass forwarded to the Procurement Officer."); refresh(); }, onError: (error) => toast.error(error.message) });
  const createAbstract = trpc.procurement.preCanvasses.createAbstract.useMutation({ onSuccess: () => { toast.success("Abstract of Canvass and lowest compliant recommendation created."); refresh(); }, onError: (error) => toast.error(error.message) });
  const ownDraftPrs = dashboard.data?.purchaseRequests.filter((pr) => pr.status === "draft" || pr.status === "procurement_review") ?? [];
  const quotesFor = (preCanvassId: number) => dashboard.data?.preCanvassQuotes.filter((quote) => quote.preCanvassId === preCanvassId) ?? [];
  const supplierMap = new Map((setup.data?.suppliers ?? []).map((supplier) => [supplier.id, supplier]));
  return <div className="mx-auto max-w-[1240px]"><PageHeader eyebrow="End-User package" title="Pre-Canvass & supplier quotes" description="Attach three supplier price quotes to the End-User PPMP and Purchase Request package before forwarding it to the Procurement Officer." action={isEndUser ? { label: "New Pre-Canvass", onClick: () => setMode(mode === "create" ? null : "create") } : undefined} />
    {mode === "create" && <FormShell title="Open Pre-Canvass" description="This form-ready workspace links the price canvass to an existing End-User Purchase Request." icon={<FileSearch className="h-4 w-4" />} className="mt-7" onSubmit={(event) => { event.preventDefault(); const value = new FormData(event.currentTarget).get("purchaseRequestId"); if (!value) return toast.error("Select the Purchase Request that requires Pre-Canvass quotes."); create.mutate({ purchaseRequestId: Number(value) }); }}><div className="mt-5 flex flex-col gap-3 sm:flex-row sm:items-end"><div className="w-full sm:max-w-xl"><Label className="text-[11px] font-semibold">Purchase Request</Label><Select name="purchaseRequestId"><SelectTrigger className="mt-1.5"><SelectValue placeholder="Select your Purchase Request" /></SelectTrigger><SelectContent>{ownDraftPrs.map((pr) => <SelectItem key={pr.id} value={String(pr.id)}>{pr.prNumber} — {pr.purpose}</SelectItem>)}</SelectContent></Select></div><Button disabled={create.isPending || !ownDraftPrs.length} className="h-9 rounded-[4px] bg-[#7b1e1e] text-xs hover:bg-[#641818]">{create.isPending && <LoaderCircle className="mr-1.5 h-3.5 w-3.5 animate-spin" />}Open Pre-Canvass</Button></div></FormShell>}
    {mode === "quote" && <PreCanvassQuoteForm preCanvasses={dashboard.data?.preCanvasses ?? []} suppliers={setup.data?.suppliers ?? []} isSaving={addQuote.isPending} onCancel={() => setMode(null)} onCreate={(input) => addQuote.mutate(input)} />}
    <div className="mt-7">{dashboard.isLoading ? <Loading label="Loading Pre-Canvass packages" /> : dashboard.data?.preCanvasses.length ? <RecordTable><RecordTableHeader><tr><th className="px-4 py-3 font-semibold">Pre-Canvass</th><th className="px-4 py-3 font-semibold">Linked PR</th><th className="px-4 py-3 font-semibold">Supplier quotes</th><th className="px-4 py-3 font-semibold">Status</th><th className="px-4 py-3 font-semibold">Action</th></tr></RecordTableHeader><tbody className="divide-y divide-[#efebe4]">{dashboard.data.preCanvasses.map((record) => { const quotes = quotesFor(record.id); const hasAbstract = dashboard.data?.abstractsOfCanvass.some((abstract) => abstract.preCanvassId === record.id); return <tr key={record.id}><td className="px-4 py-3 font-semibold text-[#7b1e1e]">{record.preCanvassNumber}</td><td className="px-4 py-3 text-[#65717e]">PR #{record.purchaseRequestId}</td><td className="px-4 py-3"><StatusBadge tone={quotes.length >= 3 ? "approved" : "pending"}>{quotes.length}/3 SUPPLIERS</StatusBadge></td><td className="px-4 py-3"><StatusBadge tone={tone(record.status)}>{record.status.replaceAll("_", " ").toUpperCase()}</StatusBadge></td><td className="px-4 py-3"><div className="flex flex-wrap gap-2">{isEndUser && record.status === "draft" && <><Button size="sm" variant="outline" onClick={() => setMode("quote")} className="h-7 rounded-[4px] text-[10px]"><Plus className="mr-1 h-3 w-3" />Add quote</Button><Button size="sm" disabled={quotes.length < 3 || submit.isPending} onClick={() => submit.mutate({ preCanvassId: record.id })} className="h-7 rounded-[4px] bg-[#7b1e1e] text-[10px] hover:bg-[#641818]">Forward package</Button></>}{isProcurement && record.status === "submitted" && !hasAbstract && <Button size="sm" disabled={createAbstract.isPending} onClick={() => createAbstract.mutate({ preCanvassId: record.id })} className="h-7 rounded-[4px] bg-[#7b1e1e] text-[10px] hover:bg-[#641818]">Create abstract</Button>}{hasAbstract && <span className="text-[11px] text-[#77818d]">Abstract ready</span>}</div></td></tr>; })}</tbody></RecordTable> : <EmptyWorkspace eyebrow="Pre-Canvass" title="No Pre-Canvass packages have been created." description="End-Users create a PPMP-linked Purchase Request, attach three supplier quotes, and forward the complete package to Procurement." />}</div>
    {dashboard.data?.preCanvasses.length ? <PreCanvassComparison records={dashboard.data.preCanvasses} quotes={dashboard.data.preCanvassQuotes} supplierMap={supplierMap} /> : null}
  </div>;
}

function PreCanvassQuoteForm({ preCanvasses, suppliers, isSaving, onCancel, onCreate }: { preCanvasses: Array<{ id: number; preCanvassNumber: string; status: string }>; suppliers: Array<{ id: number; supplierCode: string; companyName: string }>; isSaving: boolean; onCancel: () => void; onCreate: (input: { preCanvassId: number; supplierId: number; totalPrice: number; deliveryDays: number; isCompliant: boolean; notes?: string }) => void }) {
  const [preCanvassId, setPreCanvassId] = useState(""); const [supplierId, setSupplierId] = useState(""); const [totalPrice, setTotalPrice] = useState(""); const [deliveryDays, setDeliveryDays] = useState(""); const [isCompliant, setIsCompliant] = useState("yes"); const [notes, setNotes] = useState("");
  const openRecords = preCanvasses.filter((record) => record.status === "draft");
  return <FormShell title="Pre-Canvass supplier quote" description="Form-ready quote entry for the End-User's mandatory three supplier canvass." icon={<ClipboardList className="h-4 w-4" />} className="mt-7" onSubmit={(event) => { event.preventDefault(); if (!preCanvassId || !supplierId || Number(totalPrice) <= 0 || Number(deliveryDays) < 0) return toast.error("Complete the Pre-Canvass, supplier, price, and delivery fields."); onCreate({ preCanvassId: Number(preCanvassId), supplierId: Number(supplierId), totalPrice: Number(totalPrice), deliveryDays: Number(deliveryDays), isCompliant: isCompliant === "yes", notes: notes.trim() || undefined }); }}><div className="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-3"><Field label="Pre-Canvass"><Select value={preCanvassId} onValueChange={setPreCanvassId}><SelectTrigger><SelectValue placeholder="Select Pre-Canvass" /></SelectTrigger><SelectContent>{openRecords.map((record) => <SelectItem key={record.id} value={String(record.id)}>{record.preCanvassNumber}</SelectItem>)}</SelectContent></Select></Field><Field label="Supplier"><Select value={supplierId} onValueChange={setSupplierId}><SelectTrigger><SelectValue placeholder="Select supplier" /></SelectTrigger><SelectContent>{suppliers.map((supplier) => <SelectItem key={supplier.id} value={String(supplier.id)}>{supplier.supplierCode} — {supplier.companyName}</SelectItem>)}</SelectContent></Select></Field><Field label="Quoted amount"><Input type="number" min="0.01" step="0.01" value={totalPrice} onChange={(event) => setTotalPrice(event.target.value)} placeholder="0.00" /></Field><Field label="Delivery days"><Input type="number" min="0" value={deliveryDays} onChange={(event) => setDeliveryDays(event.target.value)} placeholder="0" /></Field><Field label="Compliance"><Select value={isCompliant} onValueChange={setIsCompliant}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="yes">Compliant</SelectItem><SelectItem value="no">Non-compliant</SelectItem></SelectContent></Select></Field><Field label="Notes"><Input value={notes} onChange={(event) => setNotes(event.target.value)} placeholder="Optional notes" /></Field></div><div className="mt-5 flex justify-end gap-2"><Button type="button" variant="outline" onClick={onCancel} className="h-9 rounded-[4px] text-xs">Cancel</Button><Button disabled={isSaving || !openRecords.length || !suppliers.length} className="h-9 rounded-[4px] bg-[#7b1e1e] text-xs hover:bg-[#641818]">{isSaving && <LoaderCircle className="mr-1.5 h-3.5 w-3.5 animate-spin" />}Record quote</Button></div></FormShell>;
}

function PreCanvassComparison({ records, quotes, supplierMap }: { records: Array<{ id: number; preCanvassNumber: string }>; quotes: Array<{ id: number; preCanvassId: number; supplierId: number; totalPrice: string; deliveryDays: number; isCompliant: number }>; supplierMap: Map<number, { companyName: string }> }) {
  return <div className="flat-panel mt-6"><div className="border-b border-[#ece8df] px-5 py-4"><p className="text-sm font-semibold text-[#34404e]">Pre-Canvass comparison</p><p className="mt-1 text-[11px] text-[#77818d]">The lowest compliant supplier is highlighted for the Procurement Officer's Abstract of Canvass recommendation.</p></div>{records.map((record) => { const rows = quotes.filter((quote) => quote.preCanvassId === record.id); const lowest = rows.filter((quote) => quote.isCompliant === 1).sort((a, b) => Number(a.totalPrice) - Number(b.totalPrice))[0]; return <div key={record.id} className="border-b border-[#efebe4] last:border-b-0"><p className="px-5 py-3 text-xs font-semibold text-[#7b1e1e]">{record.preCanvassNumber}</p>{rows.length ? <RecordTable className="border-x-0 border-b-0"><RecordTableHeader><tr><th className="px-4 py-3 font-semibold">Supplier</th><th className="px-4 py-3 font-semibold">Quote</th><th className="px-4 py-3 font-semibold">Delivery</th><th className="px-4 py-3 font-semibold">Compliance</th><th className="px-4 py-3 font-semibold">Recommendation</th></tr></RecordTableHeader><tbody className="divide-y divide-[#efebe4]">{rows.map((quote) => <tr key={quote.id} className={lowest?.id === quote.id ? "bg-[#fffaf0]" : ""}><td className="px-4 py-3">{supplierMap.get(quote.supplierId)?.companyName || `Supplier #${quote.supplierId}`}</td><td className="px-4 py-3">{money(quote.totalPrice)}</td><td className="px-4 py-3">{quote.deliveryDays} day(s)</td><td className="px-4 py-3"><StatusBadge tone={quote.isCompliant ? "approved" : "returned"}>{quote.isCompliant ? "COMPLIANT" : "NON-COMPLIANT"}</StatusBadge></td><td className="px-4 py-3">{lowest?.id === quote.id ? <StatusBadge tone="pending">LOWEST COMPLIANT</StatusBadge> : "—"}</td></tr>)}</tbody></RecordTable> : <p className="px-5 pb-4 text-[11px] text-[#77818d]">No supplier quotes recorded yet.</p>}</div>; })}</div>;
}

export function ExecutionPage() {
  const { user } = useAuth(); const role = user ? normalizeProcurementRole(user.role) : "end_user"; const isProcurement = role === "procurement_officer" || role === "admin"; const isApprover = role === "administrative_approver" || role === "admin";
  const [mode, setMode] = useState<"delivery" | "pmr" | null>(null); const dashboard = trpc.procurement.dashboard.useQuery(undefined, { retry: false }); const utils = trpc.useUtils(); const refresh = () => void utils.procurement.dashboard.invalidate();
  const decide = trpc.procurement.preCanvasses.decideAbstract.useMutation({ onSuccess: () => { toast.success("Administrative decision recorded."); refresh(); }, onError: (error) => toast.error(error.message) });
  const issue = trpc.procurement.preCanvasses.issuePurchaseOrder.useMutation({ onSuccess: () => { toast.success("Purchase Order issued."); refresh(); }, onError: (error) => toast.error(error.message) });
  const delivery = trpc.procurement.preCanvasses.recordDelivery.useMutation({ onSuccess: () => { toast.success("Supplier delivery recorded."); setMode(null); refresh(); }, onError: (error) => toast.error(error.message) });
  const pmr = trpc.procurement.preCanvasses.logPmr.useMutation({ onSuccess: () => { toast.success("PMR logged and Purchase Order closed."); setMode(null); refresh(); }, onError: (error) => toast.error(error.message) });
  return <div className="mx-auto max-w-[1240px]"><PageHeader eyebrow="Post-review execution" title="Abstract, approval, PO & PMR" description="Procurement recommends the lowest compliant supplier; the Administrative Approver decides; Procurement then issues the PO, records delivery, and logs the PMR." />
    <div className="mt-7 grid gap-6 xl:grid-cols-2"><section className="flat-panel"><div className="border-b border-[#ece8df] px-5 py-4"><p className="text-sm font-semibold text-[#34404e]">Abstracts of Canvass & recommendation</p><p className="mt-1 text-[11px] text-[#77818d]">Recommendations are based on the three supplier Pre-Canvass comparison.</p></div>{dashboard.data?.abstractsOfCanvass.length ? <div className="divide-y divide-[#efebe4]">{dashboard.data.abstractsOfCanvass.map((abstract) => <div key={abstract.id} className="flex flex-wrap items-center justify-between gap-4 p-5"><div><p className="text-xs font-semibold text-[#7b1e1e]">{abstract.abstractNumber}</p><p className="mt-1 text-[11px] text-[#72808c]">Pre-Canvass #{abstract.preCanvassId} · Supplier #{abstract.recommendedSupplierId}</p><p className="mt-1 text-[11px] leading-5 text-[#65717e]">{abstract.recommendationReason}</p><div className="mt-2"><StatusBadge tone={tone(abstract.status)}>{abstract.status.toUpperCase()}</StatusBadge></div></div><div className="flex gap-2">{isApprover && abstract.status === "recommended" && <><Button size="sm" onClick={() => decide.mutate({ preCanvassId: abstract.preCanvassId, decision: "approved" })} className="h-7 rounded-[4px] bg-[#7b1e1e] text-[10px] hover:bg-[#641818]">Approve</Button><Button size="sm" variant="outline" onClick={() => decide.mutate({ preCanvassId: abstract.preCanvassId, decision: "rejected" })} className="h-7 rounded-[4px] text-[10px]">Reject</Button></>}{isProcurement && abstract.status === "approved" && <Button size="sm" onClick={() => issue.mutate({ preCanvassId: abstract.preCanvassId })} className="h-7 rounded-[4px] bg-[#7b1e1e] text-[10px] hover:bg-[#641818]">Issue PO</Button>}</div></div>)}</div> : <PanelEmpty text="No Abstract of Canvass is awaiting approval." />}</section>
      <section className="flat-panel"><div className="border-b border-[#ece8df] px-5 py-4"><p className="text-sm font-semibold text-[#34404e]">Purchase Orders, delivery & PMR</p><p className="mt-1 text-[11px] text-[#77818d]">Delivery and PMR record shells will accept the official forms when provided.</p></div>{dashboard.data?.purchaseOrders.length ? <div className="divide-y divide-[#efebe4]">{dashboard.data.purchaseOrders.map((po) => <div key={po.id} className="flex flex-wrap items-center justify-between gap-4 p-5"><div><p className="text-xs font-semibold text-[#7b1e1e]">{po.poNumber}</p><p className="mt-1 text-[11px] text-[#72808c]">{money(po.totalAmount)} · Supplier #{po.supplierId}</p><div className="mt-2"><StatusBadge tone={tone(po.status)}>{po.status.replaceAll("_", " ").toUpperCase()}</StatusBadge></div></div>{isProcurement && <div className="flex gap-2">{po.status === "issued" && <Button size="sm" onClick={() => setMode("delivery")} className="h-7 rounded-[4px] bg-[#7b1e1e] text-[10px] hover:bg-[#641818]">Record delivery</Button>}{po.status === "delivered" && <Button size="sm" onClick={() => setMode("pmr")} className="h-7 rounded-[4px] bg-[#7b1e1e] text-[10px] hover:bg-[#641818]">Log PMR</Button>}</div>}</div>)}</div> : <PanelEmpty text="No Purchase Orders have been issued from approved Abstracts of Canvass." />}</section></div>
    {mode === "delivery" && <DeliveryForm purchaseOrders={dashboard.data?.purchaseOrders.filter((po) => po.status === "issued") ?? []} saving={delivery.isPending} onCancel={() => setMode(null)} onSave={(input) => delivery.mutate(input)} />}{mode === "pmr" && <PmrForm purchaseOrders={dashboard.data?.purchaseOrders.filter((po) => po.status === "delivered") ?? []} saving={pmr.isPending} onCancel={() => setMode(null)} onSave={(input) => pmr.mutate(input)} />}
  </div>;
}

function DeliveryForm({ purchaseOrders, saving, onCancel, onSave }: { purchaseOrders: Array<{ id: number; poNumber: string }>; saving: boolean; onCancel: () => void; onSave: (input: { purchaseOrderId: number; receiptNumber: string; remarks?: string }) => void }) { const [purchaseOrderId, setPurchaseOrderId] = useState(""); const [receiptNumber, setReceiptNumber] = useState(""); const [remarks, setRemarks] = useState(""); return <FormShell title="Supplier delivery record" description="Form-ready delivery record; official receiving documents can be attached when provided." className="mt-6" icon={<PackageCheck className="h-4 w-4" />} onSubmit={(event) => { event.preventDefault(); if (!purchaseOrderId || !receiptNumber.trim()) return toast.error("Select the issued Purchase Order and enter its delivery receipt reference."); onSave({ purchaseOrderId: Number(purchaseOrderId), receiptNumber: receiptNumber.trim(), remarks: remarks.trim() || undefined }); }}><div className="mt-5 grid gap-4 sm:grid-cols-2"><Field label="Issued Purchase Order"><Select value={purchaseOrderId} onValueChange={setPurchaseOrderId}><SelectTrigger><SelectValue placeholder="Select PO" /></SelectTrigger><SelectContent>{purchaseOrders.map((po) => <SelectItem key={po.id} value={String(po.id)}>{po.poNumber}</SelectItem>)}</SelectContent></Select></Field><Field label="Delivery receipt reference"><Input value={receiptNumber} onChange={(event) => setReceiptNumber(event.target.value)} placeholder="DR-0001" /></Field><div className="sm:col-span-2"><Field label="Delivery remarks"><Textarea value={remarks} onChange={(event) => setRemarks(event.target.value)} placeholder="Optional receiving or delivery notes." /></Field></div></div><FormActions saving={saving} onCancel={onCancel} label="Record delivery" /></FormShell>; }
function PmrForm({ purchaseOrders, saving, onCancel, onSave }: { purchaseOrders: Array<{ id: number; poNumber: string }>; saving: boolean; onCancel: () => void; onSave: (input: { purchaseOrderId: number; pmrNumber: string; remarks?: string }) => void }) { const [purchaseOrderId, setPurchaseOrderId] = useState(""); const [pmrNumber, setPmrNumber] = useState(""); const [remarks, setRemarks] = useState(""); return <FormShell title="PMR log" description="Form-ready PMR close-out record; official PMR fields can be mapped when the form is provided." className="mt-6" icon={<CheckCircle2 className="h-4 w-4" />} onSubmit={(event) => { event.preventDefault(); if (!purchaseOrderId || !pmrNumber.trim()) return toast.error("Select the delivered Purchase Order and enter its PMR reference."); onSave({ purchaseOrderId: Number(purchaseOrderId), pmrNumber: pmrNumber.trim(), remarks: remarks.trim() || undefined }); }}><div className="mt-5 grid gap-4 sm:grid-cols-2"><Field label="Delivered Purchase Order"><Select value={purchaseOrderId} onValueChange={setPurchaseOrderId}><SelectTrigger><SelectValue placeholder="Select PO" /></SelectTrigger><SelectContent>{purchaseOrders.map((po) => <SelectItem key={po.id} value={String(po.id)}>{po.poNumber}</SelectItem>)}</SelectContent></Select></Field><Field label="PMR reference"><Input value={pmrNumber} onChange={(event) => setPmrNumber(event.target.value)} placeholder="PMR-0001" /></Field><div className="sm:col-span-2"><Field label="PMR remarks"><Textarea value={remarks} onChange={(event) => setRemarks(event.target.value)} placeholder="Optional inspection or close-out notes." /></Field></div></div><FormActions saving={saving} onCancel={onCancel} label="Log PMR & close PO" /></FormShell>; }
function FormActions({ saving, onCancel, label }: { saving: boolean; onCancel: () => void; label: string }) { return <div className="mt-6 flex justify-end gap-2"><Button type="button" variant="outline" onClick={onCancel} className="h-9 rounded-[4px] text-xs">Cancel</Button><Button disabled={saving} className="h-9 rounded-[4px] bg-[#7b1e1e] text-xs hover:bg-[#641818]">{saving && <LoaderCircle className="mr-1.5 h-3.5 w-3.5 animate-spin" />}{label}</Button></div>; }
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <div><Label className="text-[11px] font-semibold text-[#4c5664]">{label}</Label><div className="mt-1.5">{children}</div></div>; }
function PanelEmpty({ text }: { text: string }) { return <div className="p-8 text-center text-[11px] leading-5 text-[#72808c]">{text}</div>; }
function Loading({ label }: { label: string }) { return <div className="flat-panel grid min-h-72 place-items-center text-center"><div><LoaderCircle className="mx-auto h-5 w-5 animate-spin text-[#7b1e1e]" /><p className="mt-3 text-xs text-[#6e7885]">{label}</p></div></div>; }
