import { useCallback, useEffect, useState } from "react";
import { Link } from "wouter";
import DefenseShell from "@/components/defense/DefenseShell";
import { PwAlert, PwButton, PwPanel, PwStatusBadge, SyntheticDataLabel } from "@/components/defense/PwComponents";
import { demoGovernanceRepository } from "@/features/demo/data/demoGovernanceRepository";
import { SEEDED_REQUEST } from "@/features/demo/data/procurement.seed";
import { type GovernanceDecision, type GovernanceSnapshot, type QuoteEvaluation } from "@/features/demo/domain/governance";

const money = (value: number) => `£${value.toLocaleString("en-GB")}`;
const dateTime = (value: string) => new Date(value).toLocaleString("en-GB", { dateStyle: "medium", timeStyle: "short" });
const decisionLabels: Record<GovernanceDecision, string> = { approve: "Approve recommendation", modify: "Modify recommendation", reject: "Reject recommendation", request_evidence: "Request evidence" };

function PageIntro({ title, description }: { title: string; description: string }) {
  return <div style={{ marginBottom: "var(--pw-space-6)" }}><div style={{ display: "flex", justifyContent: "space-between", gap: "var(--pw-space-4)", alignItems: "flex-start", flexWrap: "wrap" }}><div><h1 className="pw-page-title" style={{ marginBottom: "var(--pw-space-2)" }}>{title}</h1><p className="pw-supporting-text">{description}</p></div><SyntheticDataLabel /></div></div>;
}

function Loading() { return <PwPanel variant="subtle"><p className="pw-supporting-text">Loading deterministic validation state…</p></PwPanel>; }

function EvaluationTable({ evaluations, onInspect }: { evaluations: QuoteEvaluation[]; onInspect?: (evaluation: QuoteEvaluation) => void }) {
  return <PwPanel variant="default" style={{ padding: 0, overflow: "hidden" }}><div style={{ overflowX: "auto" }}><table style={{ width: "100%", borderCollapse: "collapse" }}><thead><tr style={{ background: "var(--pw-surface-subtle)", borderBottom: "1px solid var(--pw-border)" }}>{["Supplier", "Price", "Score", "Eligibility", "Validation", "Evidence"].map((heading) => <th key={heading} scope="col" style={{ padding: "12px 16px", textAlign: "left", fontSize: "var(--pw-font-size-xs)", fontWeight: 600, color: "var(--pw-text-muted)", textTransform: "uppercase", letterSpacing: "0.08em", whiteSpace: "nowrap" }}>{heading}</th>)}</tr></thead><tbody>{evaluations.map((evaluation) => { const pendingEvidence = evaluation.reviewState === "pending_evidence"; const blocked = evaluation.reviewState === "over_budget"; return <tr key={evaluation.quote.id} style={{ borderBottom: "1px solid var(--pw-border)", background: evaluation.eligible ? "var(--pw-success-surface)" : undefined }}><td style={{ padding: "14px 16px", fontWeight: 600 }}>{evaluation.quote.supplierName}</td><td style={{ padding: "14px 16px" }}>{money(evaluation.quote.total)}</td><td style={{ padding: "14px 16px", fontWeight: 700 }}>{evaluation.score.toFixed(1)}</td><td style={{ padding: "14px 16px" }}><PwStatusBadge variant={evaluation.eligible ? "approved" : pendingEvidence ? "review" : "missing-evidence"}>{evaluation.eligible ? "Eligible" : pendingEvidence ? "Pending evidence" : "Blocked"}</PwStatusBadge></td><td style={{ padding: "14px 16px" }}><PwStatusBadge variant={blocked ? "missing-evidence" : pendingEvidence ? "review" : "approved"}>{blocked ? "Over budget" : pendingEvidence ? "Evidence requested" : "Passed"}</PwStatusBadge></td><td style={{ padding: "14px 16px" }}><PwButton type="button" variant="text" onClick={() => onInspect?.(evaluation)} aria-label={`Inspect validation evidence for ${evaluation.quote.supplierName}`}>Inspect evidence</PwButton></td></tr>; })}</tbody></table></div></PwPanel>;
}

export function DemoValidationPage() {
  const [snapshot, setSnapshot] = useState<GovernanceSnapshot | null>(null);
  const [selected, setSelected] = useState<QuoteEvaluation | null>(null);
  useEffect(() => { void demoGovernanceRepository.getSnapshot().then(setSnapshot); }, []);
  if (!snapshot) return <DefenseShell pageTitle="Validation"><Loading /></DefenseShell>;
  const passed = snapshot.evaluations.filter((evaluation) => evaluation.eligible).length;
  return <DefenseShell pageTitle="Validation"><PageIntro title="Validation evidence" description="Inspect the deterministic checks that make each supplier eligible or pending evidence before a recommendation reaches a human approver." /><div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(180px, 1fr))", gap: "var(--pw-space-3)", marginBottom: "var(--pw-space-6)" }}><Metric label="Quotes reviewed" value={String(snapshot.evaluations.length)} /><Metric label="Eligible quotes" value={String(passed)} /><Metric label="Pending evidence" value={String(snapshot.evaluations.filter((evaluation) => evaluation.reviewState === "pending_evidence").length)} /><Metric label="Recommendation" value={snapshot.recommendedSupplierId ?? "None"} /></div><PwAlert variant="info" title="Validation rule" message="A missing mandatory evidence item flags a supplier for submission. Supplier C remains visible and can receive an evidence request, but cannot be recommended until the evidence is supplied." /><div style={{ marginTop: "var(--pw-space-6)" }}><EvaluationTable evaluations={snapshot.evaluations} onInspect={setSelected} /></div>{selected && <EvidenceInspector evaluation={selected} onClose={() => setSelected(null)} />}</DefenseShell>;
}

function EvidenceInspector({ evaluation, onClose }: { evaluation: QuoteEvaluation; onClose: () => void }) {
  return <div role="dialog" aria-modal="true" aria-labelledby="evidence-title" style={{ position: "fixed", inset: 0, background: "rgba(6,47,54,.28)", display: "grid", placeItems: "center", padding: "var(--pw-space-4)", zIndex: 20 }}><PwPanel variant={evaluation.eligible ? "selected" : evaluation.reviewState === "pending_evidence" ? "warning" : "error"} style={{ width: "min(680px, 100%)", maxHeight: "90vh", overflowY: "auto" }}><div style={{ display: "flex", justifyContent: "space-between", gap: 12, alignItems: "flex-start" }}><div><h2 id="evidence-title" className="pw-section-title" style={{ margin: 0 }}>{evaluation.quote.supplierName} validation evidence</h2><p className="pw-supporting-text" style={{ marginTop: 6 }}>Score {evaluation.score.toFixed(1)} · {money(evaluation.quote.total)} · {evaluation.quote.deliveryDays} days · {evaluation.quote.warrantyYears}-year warranty</p></div><PwButton type="button" variant="text" onClick={onClose}>Close</PwButton></div><div style={{ display: "grid", gap: "var(--pw-space-3)", marginTop: "var(--pw-space-5)" }}>{evaluation.findings.map((finding) => <div key={finding.id} style={{ borderLeft: `4px solid ${finding.severity === "error" ? "var(--pw-danger-text)" : finding.severity === "warning" ? "var(--pw-warning-text)" : "var(--pw-success-text)"}`, padding: "var(--pw-space-3)", background: "var(--pw-surface-subtle)" }}><p style={{ margin: 0, fontWeight: 700 }}>{finding.title}</p><p className="pw-supporting-text" style={{ marginTop: 4 }}>{finding.message}</p>{finding.evidenceIds.length > 0 && <p style={{ margin: "6px 0 0", fontSize: "var(--pw-font-size-xs)", color: "var(--pw-text-muted)" }}>Evidence references: {finding.evidenceIds.join(", ")}</p>}</div>)}</div></PwPanel></div>;
}

export function DemoApprovalsPage() {
  const [snapshot, setSnapshot] = useState<GovernanceSnapshot | null>(null);
  const [action, setAction] = useState<GovernanceDecision>("approve");
  const [reason, setReason] = useState("");
  const [message, setMessage] = useState<{ variant: "success" | "error"; text: string } | null>(null);
  const refresh = useCallback(() => { void demoGovernanceRepository.getSnapshot().then(setSnapshot); }, []);
  useEffect(() => { refresh(); }, [refresh]);
  if (!snapshot) return <DefenseShell pageTitle="Approvals"><Loading /></DefenseShell>;
  const submit = async () => { setMessage(null); try { await demoGovernanceRepository.decide(action, reason); setReason(""); setMessage({ variant: "success", text: `${decisionLabels[action]} was recorded in the immutable audit trail.` }); refresh(); } catch (error) { setMessage({ variant: "error", text: error instanceof Error ? error.message : "The decision could not be recorded." }); } };
  return <DefenseShell pageTitle="Approvals">
    <PageIntro title="Approval queue" description="Review the transparent recommendation, then record an explicit human decision. The recommendation never commits procurement by itself." />
    {message && <div style={{ marginBottom: "var(--pw-space-4)" }}><PwAlert variant={message.variant} title={message.variant === "success" ? "Decision recorded" : "Decision validation"} message={message.text} /></div>}
    <div style={{ display: "grid", gridTemplateColumns: "minmax(0, 1.25fr) minmax(300px, .75fr)", gap: "var(--pw-space-6)", alignItems: "start" }}>
      <PwPanel variant="default">
        <div style={{ display: "flex", justifyContent: "space-between", gap: 12, alignItems: "flex-start" }}>
          <div><p className="pw-eyebrow">{SEEDED_REQUEST.id}</p><h2 className="pw-section-title" style={{ marginTop: 8 }}>{SEEDED_REQUEST.title}</h2><p className="pw-supporting-text" style={{ marginTop: 6 }}>Budget {money(SEEDED_REQUEST.budget)} · {SEEDED_REQUEST.quantity} units · Required by {SEEDED_REQUEST.requiredBy}</p></div>
          <PwStatusBadge variant={snapshot.status === "pending" ? "pending-approval" : snapshot.status === "approved" ? "approved" : snapshot.status === "rejected" ? "rejected" : "review"}>{snapshot.status.replace("_", " ")}</PwStatusBadge>
        </div>
        <div style={{ marginTop: "var(--pw-space-6)" }}><EvaluationTable evaluations={snapshot.evaluations} /></div>
      </PwPanel>
      <DecisionForm action={action} setAction={setAction} reason={reason} setReason={setReason} status={snapshot.status} onSubmit={submit} />
    </div>
    {snapshot.decision && <PwPanel variant="selected" style={{ marginTop: "var(--pw-space-6)" }}>
      <p className="pw-panel-title">Recorded human decision</p>
      <p className="pw-supporting-text" style={{ marginTop: 6 }}>{decisionLabels[snapshot.decision.action]} by {snapshot.decision.actor} on {dateTime(snapshot.decision.timestamp)}.</p>
      <p style={{ margin: "8px 0 0" }}><strong>Reason:</strong> {snapshot.decision.reason || "Approval accepted the eligible recommendation."}</p>
      {snapshot.evidenceDeadline && <p style={{ margin: "8px 0 0", color: "var(--pw-warning-text)" }}><strong>Evidence due:</strong> {dateTime(snapshot.evidenceDeadline)}</p>}
    </PwPanel>}
  </DefenseShell>;
}

function DecisionForm({ action, setAction, reason, setReason, status, onSubmit }: { action: GovernanceDecision; setAction: (value: GovernanceDecision) => void; reason: string; setReason: (value: string) => void; status: string; onSubmit: () => void }) {
  const requiresReason = action !== "approve";
  return <PwPanel variant="subtle"><h2 className="pw-section-title">Human decision</h2><p className="pw-supporting-text" style={{ marginTop: 6 }}>Select an action. Non-approval actions require a meaningful reason so the audit record explains the decision.</p><label htmlFor="governance-action" style={{ display: "block", marginTop: "var(--pw-space-5)", fontSize: "var(--pw-font-size-sm)", fontWeight: 600 }}>Decision</label><select id="governance-action" value={action} onChange={(event) => setAction(event.target.value as GovernanceDecision)} disabled={status !== "pending"} style={{ width: "100%", minHeight: 42, marginTop: 6, padding: "0 10px", border: "1px solid var(--pw-border-strong)", borderRadius: "var(--pw-radius-md)", background: "var(--pw-surface)", color: "var(--pw-text)" }}>{Object.entries(decisionLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select><label htmlFor="governance-reason" style={{ display: "block", marginTop: "var(--pw-space-4)", fontSize: "var(--pw-font-size-sm)", fontWeight: 600 }}>Reason {requiresReason ? "(required)" : "(optional)"}</label><textarea id="governance-reason" value={reason} onChange={(event) => setReason(event.target.value)} disabled={status !== "pending"} placeholder={requiresReason ? "Explain the evidence, correction, or decision…" : "Optional approval note…"} rows={5} style={{ width: "100%", marginTop: 6, padding: 10, border: "1px solid var(--pw-border-strong)", borderRadius: "var(--pw-radius-md)", background: "var(--pw-surface)", color: "var(--pw-text)", resize: "vertical" }} />{requiresReason && reason.trim().length > 0 && reason.trim().length < 10 && <p role="alert" style={{ color: "var(--pw-danger-text)", fontSize: "var(--pw-font-size-xs)" }}>Enter at least 10 characters so the decision is auditable.</p>}<PwButton type="button" style={{ marginTop: "var(--pw-space-4)", width: "100%" }} disabled={status !== "pending" || (requiresReason && reason.trim().length < 10)} variant={action === "reject" ? "danger" : "primary"} onClick={onSubmit}>{decisionLabels[action]}</PwButton></PwPanel>;
}

export function DemoAuditPage() {
  const [snapshot, setSnapshot] = useState<GovernanceSnapshot | null>(null);
  useEffect(() => { void demoGovernanceRepository.getSnapshot().then(setSnapshot); }, []);
  if (!snapshot) return <DefenseShell pageTitle="Audit log"><Loading /></DefenseShell>;
  return <DefenseShell pageTitle="Audit log"><PageIntro title="Audit log" description="A chronological, append-only record of system validation and human governance actions for the synthetic request." /><PwAlert variant="info" title="Write-once presentation" message="Every event is displayed as immutable. The demo offers no edit or delete action for audit records." /><PwPanel variant="default" style={{ padding: 0, overflow: "hidden", marginTop: "var(--pw-space-6)" }}><div style={{ overflowX: "auto" }}><table style={{ width: "100%", borderCollapse: "collapse" }}><thead><tr style={{ background: "var(--pw-surface-subtle)", borderBottom: "1px solid var(--pw-border)" }}><th scope="col" style={th}>Time</th><th scope="col" style={th}>Actor</th><th scope="col" style={th}>Action</th><th scope="col" style={th}>Detail</th><th scope="col" style={th}>Integrity</th></tr></thead><tbody>{snapshot.audit.map((event) => <tr key={event.id} style={{ borderBottom: "1px solid var(--pw-border)" }}><td style={td}>{dateTime(event.timestamp)}</td><td style={td}>{event.actor}</td><td style={td}><strong>{event.action.replaceAll("_", " ")}</strong></td><td style={td}>{event.detail}</td><td style={td}><PwStatusBadge variant="approved">Immutable</PwStatusBadge></td></tr>)}</tbody></table></div></PwPanel><p className="pw-supporting-text" style={{ marginTop: "var(--pw-space-4)" }}>Make a decision in <Link href="/demo/approvals" style={{ color: "var(--pw-brand-800)", fontWeight: 700 }}>Approvals</Link>, then return here to see the appended event.</p></DefenseShell>;
}

const th: React.CSSProperties = { padding: "12px 16px", textAlign: "left", fontSize: "var(--pw-font-size-xs)", fontWeight: 600, color: "var(--pw-text-muted)", textTransform: "uppercase", letterSpacing: "0.08em", whiteSpace: "nowrap" };
const td: React.CSSProperties = { padding: "14px 16px", fontSize: "var(--pw-font-size-sm)", verticalAlign: "top" };

export function DemoGovernancePage() {
  return <DefenseShell pageTitle="Governance"><PageIntro title="AI and governance controls" description="Interactive controls that keep humans accountable for procurement decisions." /><div style={{ maxWidth: 860, display: "grid", gap: "var(--pw-space-4)" }}><PwPanel variant="selected"><div style={{ display: "flex", justifyContent: "space-between", gap: 12, flexWrap: "wrap" }}><div><h2 className="pw-section-title">Human authority is preserved</h2><p className="pw-supporting-text" style={{ marginTop: 6 }}>Recommendations are advisory. An explicit Administrative Approver action is required before the demo records an approval.</p></div><PwStatusBadge variant="approved">Implemented</PwStatusBadge></div><PwButton variant="primary" style={{ marginTop: "var(--pw-space-4)" }} onClick={() => { window.location.href = "/demo/approvals" }}>Open approval queue</PwButton></PwPanel><PwPanel variant="default"><h2 className="pw-section-title">Compliance evidence is required before recommendation</h2><p className="pw-supporting-text" style={{ marginTop: 6 }}>Supplier C is cheaper but flagged for missing mandatory due-diligence evidence. The validation route exposes the evidence references and rule outcome.</p><Link href="/demo/validation" style={{ display: "inline-block", marginTop: "var(--pw-space-4)", color: "var(--pw-brand-800)", fontWeight: 700 }}>Inspect validation evidence →</Link></PwPanel><PwPanel variant="default"><h2 className="pw-section-title">AI-unavailable fallback</h2><p className="pw-supporting-text" style={{ marginTop: 6 }}>The decision screen remains usable from deterministic raw comparisons. A human can request evidence, modify, reject, or approve only when the eligibility rule permits it.</p><PwStatusBadge variant="simulated">Demonstrated in Day 2</PwStatusBadge></PwPanel><PwPanel variant="default"><h2 className="pw-section-title">Auditability</h2><p className="pw-supporting-text" style={{ marginTop: 6 }}>System checks and human decisions append immutable events. No UI action edits or deletes existing events.</p><Link href="/demo/audit" style={{ display: "inline-block", marginTop: "var(--pw-space-4)", color: "var(--pw-brand-800)", fontWeight: 700 }}>View audit log →</Link></PwPanel></div></DefenseShell>;
}

function Metric({ label, value }: { label: string; value: string }) { return <PwPanel variant="subtle" style={{ padding: "var(--pw-space-4)" }}><p style={{ margin: 0, fontSize: "var(--pw-font-size-xs)", color: "var(--pw-text-muted)", textTransform: "uppercase", letterSpacing: ".08em" }}>{label}</p><p style={{ margin: "8px 0 0", fontSize: "var(--pw-font-size-xl)", fontWeight: 700, color: "var(--pw-text)" }}>{value}</p></PwPanel>; }
