-- Generated by scripts/seed-demo-accounts.mjs. Safe to re-run.
insert into procurewise.users ("openId", name, email, "loginMethod", role)
values
  ('0060bb37-c221-4502-8d3e-8ec1d8d06776', 'Demo Admin', 'admin@procurewise.demo', 'supabase', 'admin'),
  ('0d803300-5389-4ae5-8e95-99c5c8142baa', 'Demo Administrative Approver', 'approver@procurewise.demo', 'supabase', 'administrative_approver'),
  ('634518b2-2c34-4467-8f1a-77638a1c8d4d', 'Demo Procurement Officer', 'officer@procurewise.demo', 'supabase', 'procurement_officer'),
  ('3420b985-19c1-48e2-b5a4-4dcb27ae0814', 'Demo End-User', 'enduser@procurewise.demo', 'supabase', 'end_user')
on conflict ("openId") do update
  set name = excluded.name, email = excluded.email, role = excluded.role, "updatedAt" = now();
