CREATE TABLE "abstracts_of_canvass" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "abstracts_of_canvass_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"abstractNumber" varchar(40) NOT NULL,
	"preCanvassId" integer NOT NULL,
	"recommendedSupplierId" integer NOT NULL,
	"recommendationReason" text NOT NULL,
	"openingDate" timestamp DEFAULT now() NOT NULL,
	"openingLocation" varchar(160) DEFAULT 'Basco, Batanes' NOT NULL,
	"procurementCategory" varchar(120) DEFAULT 'Supplies and materials' NOT NULL,
	"status" varchar(64) DEFAULT 'recommended' NOT NULL,
	"preparedById" integer NOT NULL,
	"decidedById" integer,
	"decisionRemarks" text,
	"createdAt" timestamp DEFAULT now() NOT NULL,
	"updatedAt" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "abstracts_of_canvass_abstractNumber_unique" UNIQUE("abstractNumber"),
	CONSTRAINT "abstracts_of_canvass_preCanvassId_unique" UNIQUE("preCanvassId")
);
--> statement-breakpoint
CREATE TABLE "app_ppmp_entries" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "app_ppmp_entries_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"fiscalYear" integer NOT NULL,
	"officeId" integer NOT NULL,
	"objectOfExpenditureId" integer NOT NULL,
	"catalogItemId" integer,
	"description" text NOT NULL,
	"papCode" varchar(80),
	"projectTitle" varchar(220),
	"modeOfProcurement" varchar(120) DEFAULT 'Small Value Procurement',
	"fundSource" varchar(160),
	"procurementSchedule" text,
	"remarks" text,
	"plannedAmount" numeric(14, 2) NOT NULL,
	"actualAmount" numeric(14, 2) DEFAULT '0.00' NOT NULL,
	"status" varchar(64) DEFAULT 'draft' NOT NULL,
	"preparedById" integer NOT NULL,
	"createdAt" timestamp DEFAULT now() NOT NULL,
	"updatedAt" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "audit_trails" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "audit_trails_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"entityType" varchar(64) NOT NULL,
	"entityId" integer NOT NULL,
	"action" varchar(100) NOT NULL,
	"performedById" integer NOT NULL,
	"performedByRole" varchar(64) NOT NULL,
	"details" json,
	"createdAt" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "bac_transmittals" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "bac_transmittals_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"transmittalNumber" varchar(48) NOT NULL,
	"purchaseRequestId" integer,
	"fromOffice" varchar(180) NOT NULL,
	"toOffice" varchar(180) NOT NULL,
	"subject" varchar(220) NOT NULL,
	"remarks" text,
	"status" varchar(64) DEFAULT 'draft' NOT NULL,
	"preparedById" integer NOT NULL,
	"sentAt" timestamp,
	"acknowledgedByName" varchar(180),
	"acknowledgedAt" timestamp,
	"createdAt" timestamp DEFAULT now() NOT NULL,
	"updatedAt" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "bac_transmittals_transmittalNumber_unique" UNIQUE("transmittalNumber")
);
--> statement-breakpoint
CREATE TABLE "budget_allotments" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "budget_allotments_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"officeId" integer NOT NULL,
	"objectOfExpenditureId" integer NOT NULL,
	"fiscalYear" integer NOT NULL,
	"allottedAmount" numeric(14, 2) NOT NULL,
	"committedAmount" numeric(14, 2) DEFAULT '0.00' NOT NULL,
	"createdById" integer NOT NULL,
	"createdAt" timestamp DEFAULT now() NOT NULL,
	"updatedAt" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "delivery_receipts" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "delivery_receipts_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"purchaseOrderId" integer NOT NULL,
	"receiptNumber" varchar(40) NOT NULL,
	"deliveredAt" timestamp DEFAULT now() NOT NULL,
	"receivedById" integer NOT NULL,
	"receivedByName" varchar(180),
	"deliveryStatus" varchar(64) DEFAULT 'complete' NOT NULL,
	"signatureReference" text,
	"remarks" text,
	"createdAt" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "delivery_receipts_purchaseOrderId_unique" UNIQUE("purchaseOrderId"),
	CONSTRAINT "delivery_receipts_receiptNumber_unique" UNIQUE("receiptNumber")
);
--> statement-breakpoint
CREATE TABLE "historical_prices" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "historical_prices_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"itemDescription" varchar(220) NOT NULL,
	"unit" varchar(40) NOT NULL,
	"unitPrice" numeric(14, 2) NOT NULL,
	"supplierId" integer,
	"purchaseOrderId" integer,
	"observedAt" timestamp DEFAULT now() NOT NULL,
	"recordedById" integer NOT NULL
);
--> statement-breakpoint
CREATE TABLE "letters_of_notice" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "letters_of_notice_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"noticeNumber" varchar(48) NOT NULL,
	"noticeType" varchar(64) DEFAULT 'other' NOT NULL,
	"purchaseRequestId" integer,
	"supplierId" integer,
	"subject" varchar(220) NOT NULL,
	"body" text NOT NULL,
	"status" varchar(64) DEFAULT 'draft' NOT NULL,
	"issuedById" integer NOT NULL,
	"issuedAt" timestamp,
	"createdAt" timestamp DEFAULT now() NOT NULL,
	"updatedAt" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "letters_of_notice_noticeNumber_unique" UNIQUE("noticeNumber")
);
--> statement-breakpoint
CREATE TABLE "mcdm_recommendations" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "mcdm_recommendations_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"preCanvassId" integer NOT NULL,
	"recommendedSupplierId" integer NOT NULL,
	"priceScore" numeric(7, 2) NOT NULL,
	"deliveryScore" numeric(7, 2) NOT NULL,
	"complianceScore" numeric(7, 2) NOT NULL,
	"totalScore" numeric(7, 2) NOT NULL,
	"rationale" text NOT NULL,
	"createdById" integer NOT NULL,
	"createdAt" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "mcdm_recommendations_preCanvassId_unique" UNIQUE("preCanvassId")
);
--> statement-breakpoint
CREATE TABLE "objects_of_expenditure" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "objects_of_expenditure_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"code" varchar(32) NOT NULL,
	"name" varchar(180) NOT NULL,
	"isActive" integer DEFAULT 1 NOT NULL,
	"createdAt" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "objects_of_expenditure_code_unique" UNIQUE("code")
);
--> statement-breakpoint
CREATE TABLE "offices" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "offices_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"code" varchar(32) NOT NULL,
	"name" varchar(160) NOT NULL,
	"isActive" integer DEFAULT 1 NOT NULL,
	"createdAt" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "offices_code_unique" UNIQUE("code")
);
--> statement-breakpoint
CREATE TABLE "pmr_logs" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pmr_logs_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"purchaseOrderId" integer NOT NULL,
	"pmrNumber" varchar(40) NOT NULL,
	"remarks" text,
	"loggedById" integer NOT NULL,
	"loggedAt" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "pmr_logs_purchaseOrderId_unique" UNIQUE("purchaseOrderId"),
	CONSTRAINT "pmr_logs_pmrNumber_unique" UNIQUE("pmrNumber")
);
--> statement-breakpoint
CREATE TABLE "pre_canvass_quotes" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pre_canvass_quotes_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"preCanvassId" integer NOT NULL,
	"supplierId" integer NOT NULL,
	"totalPrice" numeric(14, 2) NOT NULL,
	"deliveryDays" integer NOT NULL,
	"isCompliant" integer DEFAULT 1 NOT NULL,
	"notes" text,
	"quotationReference" varchar(80),
	"supplierRepresentative" varchar(160),
	"acknowledgedAt" timestamp,
	"receivedBy" varchar(160),
	"submittedAt" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "pre_canvasses" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pre_canvasses_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"preCanvassNumber" varchar(40) NOT NULL,
	"purchaseRequestId" integer NOT NULL,
	"status" varchar(64) DEFAULT 'draft' NOT NULL,
	"approvedBudget" numeric(14, 2),
	"quotationDeadline" timestamp,
	"deliveryPeriodDays" integer,
	"priceEvaluationMode" varchar(80) DEFAULT 'lot_basis',
	"preparedById" integer NOT NULL,
	"createdAt" timestamp DEFAULT now() NOT NULL,
	"updatedAt" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "pre_canvasses_preCanvassNumber_unique" UNIQUE("preCanvassNumber"),
	CONSTRAINT "pre_canvasses_purchaseRequestId_unique" UNIQUE("purchaseRequestId")
);
--> statement-breakpoint
CREATE TABLE "procurement_catalog_favorites" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "procurement_catalog_favorites_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"userId" integer NOT NULL,
	"catalogItemId" integer NOT NULL,
	"createdAt" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "procurement_catalog_items" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "procurement_catalog_items_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"source" varchar(80) DEFAULT 'Common-use supplies and equipment catalog' NOT NULL,
	"productCode" varchar(80) NOT NULL,
	"description" text NOT NULL,
	"unit" varchar(40),
	"referencePrice" numeric(14, 2) NOT NULL,
	"remarks" text,
	"imageUrl" varchar(500),
	"sourceAsOfDate" varchar(40) DEFAULT '2026-08-17' NOT NULL,
	"isActive" integer DEFAULT 1 NOT NULL,
	"createdAt" timestamp DEFAULT now() NOT NULL,
	"updatedAt" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "procurement_catalog_items_productCode_unique" UNIQUE("productCode")
);
--> statement-breakpoint
CREATE TABLE "procurement_documents" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "procurement_documents_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"entityType" varchar(64) NOT NULL,
	"entityId" integer NOT NULL,
	"documentType" varchar(80) NOT NULL,
	"originalFileName" varchar(255) NOT NULL,
	"mimeType" varchar(120) NOT NULL,
	"storageKey" varchar(512) NOT NULL,
	"storageUrl" varchar(512) NOT NULL,
	"fileSize" integer NOT NULL,
	"uploadedById" integer NOT NULL,
	"createdAt" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "procurement_documents_storageKey_unique" UNIQUE("storageKey")
);
--> statement-breakpoint
CREATE TABLE "procurement_settings" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "procurement_settings_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"entityName" varchar(180) DEFAULT 'Batanes State College' NOT NULL,
	"authorizedOfficialName" varchar(180),
	"authorizedOfficialDesignation" varchar(160),
	"chiefAccountantName" varchar(180),
	"defaultNoticeSignatory" varchar(180),
	"sessionTimeoutMinutes" integer DEFAULT 30 NOT NULL,
	"enableInAppNotifications" integer DEFAULT 1 NOT NULL,
	"notificationRefreshSeconds" integer DEFAULT 15 NOT NULL,
	"updatedById" integer,
	"updatedAt" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "purchase_orders" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "purchase_orders_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"poNumber" varchar(40) NOT NULL,
	"purchaseRequestId" integer NOT NULL,
	"rfqId" integer,
	"preCanvassId" integer,
	"supplierId" integer NOT NULL,
	"totalAmount" numeric(14, 2) NOT NULL,
	"placeOfDelivery" varchar(220),
	"scheduledDeliveryDate" timestamp,
	"deliveryTerm" varchar(120) DEFAULT 'FOB Destination',
	"paymentTerm" varchar(160) DEFAULT '15 days upon complete delivery',
	"modeOfProcurement" varchar(120),
	"fundCluster" varchar(80),
	"orsBursNumber" varchar(80),
	"fundsAvailable" numeric(14, 2),
	"authorizedOfficialName" varchar(180),
	"authorizedOfficialDesignation" varchar(160),
	"chiefAccountantName" varchar(180),
	"status" varchar(64) DEFAULT 'draft' NOT NULL,
	"generatedById" integer NOT NULL,
	"approvedById" integer,
	"createdAt" timestamp DEFAULT now() NOT NULL,
	"updatedAt" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "purchase_orders_poNumber_unique" UNIQUE("poNumber"),
	CONSTRAINT "purchase_orders_purchaseRequestId_unique" UNIQUE("purchaseRequestId"),
	CONSTRAINT "purchase_orders_rfqId_unique" UNIQUE("rfqId"),
	CONSTRAINT "purchase_orders_preCanvassId_unique" UNIQUE("preCanvassId")
);
--> statement-breakpoint
CREATE TABLE "purchase_request_items" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "purchase_request_items_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"purchaseRequestId" integer NOT NULL,
	"catalogItemId" integer,
	"description" text NOT NULL,
	"stockPropertyNo" varchar(80),
	"specification" text,
	"quantity" numeric(12, 2) NOT NULL,
	"unit" varchar(40) NOT NULL,
	"estimatedUnitCost" numeric(14, 2) NOT NULL,
	"totalCost" numeric(14, 2) NOT NULL
);
--> statement-breakpoint
CREATE TABLE "purchase_requests" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "purchase_requests_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"prNumber" varchar(40) NOT NULL,
	"purpose" text NOT NULL,
	"fundSource" varchar(160),
	"entityName" varchar(180) DEFAULT 'Batanes State College' NOT NULL,
	"fundCluster" varchar(80) DEFAULT '01101101' NOT NULL,
	"responsibilityCenterCode" varchar(80),
	"requesterDesignation" varchar(160),
	"officeId" integer NOT NULL,
	"objectOfExpenditureId" integer NOT NULL,
	"totalEstimate" numeric(14, 2) NOT NULL,
	"status" varchar(64) DEFAULT 'draft' NOT NULL,
	"requestedById" integer NOT NULL,
	"trackingToken" varchar(48) NOT NULL,
	"ppmpEntryId" integer,
	"procurementReviewedById" integer,
	"administrativeApprovedById" integer,
	"budgetReviewedById" integer,
	"supplyReviewedById" integer,
	"bacReviewedById" integer,
	"createdAt" timestamp DEFAULT now() NOT NULL,
	"submittedAt" timestamp,
	"updatedAt" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "purchase_requests_prNumber_unique" UNIQUE("prNumber"),
	CONSTRAINT "purchase_requests_trackingToken_unique" UNIQUE("trackingToken")
);
--> statement-breakpoint
CREATE TABLE "quotation_abstracts" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "quotation_abstracts_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"rfqId" integer NOT NULL,
	"recommendedSupplierId" integer NOT NULL,
	"recommendationReason" text NOT NULL,
	"status" varchar(64) DEFAULT 'draft' NOT NULL,
	"preparedById" integer NOT NULL,
	"approvedById" integer,
	"createdAt" timestamp DEFAULT now() NOT NULL,
	"updatedAt" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "quotation_abstracts_rfqId_unique" UNIQUE("rfqId")
);
--> statement-breakpoint
CREATE TABLE "rfqs" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "rfqs_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"rfqNumber" varchar(40) NOT NULL,
	"purchaseRequestId" integer NOT NULL,
	"status" varchar(64) DEFAULT 'draft' NOT NULL,
	"createdById" integer NOT NULL,
	"createdAt" timestamp DEFAULT now() NOT NULL,
	"updatedAt" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "rfqs_rfqNumber_unique" UNIQUE("rfqNumber"),
	CONSTRAINT "rfqs_purchaseRequestId_unique" UNIQUE("purchaseRequestId")
);
--> statement-breakpoint
CREATE TABLE "supplier_evaluations" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "supplier_evaluations_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"supplierId" integer NOT NULL,
	"purchaseOrderId" integer,
	"qualityScore" integer NOT NULL,
	"deliveryScore" integer NOT NULL,
	"pricingScore" integer NOT NULL,
	"complianceScore" integer NOT NULL,
	"remarks" text,
	"evaluatedById" integer NOT NULL,
	"evaluatedAt" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "supplier_quotations" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "supplier_quotations_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"rfqId" integer NOT NULL,
	"supplierId" integer NOT NULL,
	"totalPrice" numeric(14, 2) NOT NULL,
	"deliveryDays" integer NOT NULL,
	"isCompliant" integer DEFAULT 1 NOT NULL,
	"notes" text,
	"submittedAt" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "supplier_tag_assignments" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "supplier_tag_assignments_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"supplierId" integer NOT NULL,
	"supplierTagId" integer NOT NULL,
	"assignedById" integer NOT NULL,
	"createdAt" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "supplier_tags" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "supplier_tags_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(120) NOT NULL,
	"description" varchar(320),
	"isActive" integer DEFAULT 1 NOT NULL,
	"createdById" integer NOT NULL,
	"createdAt" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "supplier_tags_name_unique" UNIQUE("name")
);
--> statement-breakpoint
CREATE TABLE "suppliers" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "suppliers_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"supplierCode" varchar(40) NOT NULL,
	"companyName" varchar(180) NOT NULL,
	"contactPerson" varchar(140),
	"email" varchar(320),
	"phone" varchar(80),
	"address" text,
	"tin" varchar(80),
	"offerings" text,
	"accreditationStatus" varchar(64) DEFAULT 'pending' NOT NULL,
	"isActive" integer DEFAULT 1 NOT NULL,
	"createdById" integer NOT NULL,
	"createdAt" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "suppliers_supplierCode_unique" UNIQUE("supplierCode")
);
--> statement-breakpoint
CREATE TABLE "test_record_archives" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "test_record_archives_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"ppmpEntryId" integer NOT NULL,
	"archivedById" integer NOT NULL,
	"archiveReason" text NOT NULL,
	"archivedAt" timestamp DEFAULT now() NOT NULL,
	"cleanedAt" timestamp,
	CONSTRAINT "test_record_archives_ppmpEntryId_unique" UNIQUE("ppmpEntryId")
);
--> statement-breakpoint
CREATE TABLE "users" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "users_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"openId" varchar(64) NOT NULL,
	"name" text,
	"email" varchar(320),
	"loginMethod" varchar(64),
	"role" varchar(64) DEFAULT 'end_user' NOT NULL,
	"createdAt" timestamp DEFAULT now() NOT NULL,
	"updatedAt" timestamp DEFAULT now() NOT NULL,
	"lastSignedIn" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "users_openId_unique" UNIQUE("openId")
);
--> statement-breakpoint
CREATE TABLE "workflow_corrections" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "workflow_corrections_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"entityType" varchar(64) NOT NULL,
	"entityId" integer NOT NULL,
	"requestedById" integer NOT NULL,
	"assignedToId" integer NOT NULL,
	"reason" text NOT NULL,
	"status" varchar(64) DEFAULT 'open' NOT NULL,
	"createdAt" timestamp DEFAULT now() NOT NULL,
	"resolvedAt" timestamp
);
--> statement-breakpoint
CREATE TABLE "workflow_notifications" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "workflow_notifications_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"recipientUserId" integer NOT NULL,
	"kind" varchar(64) NOT NULL,
	"title" varchar(180) NOT NULL,
	"body" text NOT NULL,
	"entityType" varchar(64) NOT NULL,
	"entityId" integer NOT NULL,
	"readAt" timestamp,
	"createdAt" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE INDEX "app_ppmp_office_year_idx" ON "app_ppmp_entries" USING btree ("officeId","fiscalYear");--> statement-breakpoint
CREATE INDEX "audit_entity_created_idx" ON "audit_trails" USING btree ("entityType","entityId","createdAt");--> statement-breakpoint
CREATE INDEX "transmittal_pr_created_idx" ON "bac_transmittals" USING btree ("purchaseRequestId","createdAt");--> statement-breakpoint
CREATE UNIQUE INDEX "budget_allotment_office_object_year_unique" ON "budget_allotments" USING btree ("officeId","objectOfExpenditureId","fiscalYear");--> statement-breakpoint
CREATE INDEX "budget_allotment_office_year_idx" ON "budget_allotments" USING btree ("officeId","fiscalYear");--> statement-breakpoint
CREATE INDEX "historical_price_item_observed_idx" ON "historical_prices" USING btree ("itemDescription","observedAt");--> statement-breakpoint
CREATE INDEX "notice_pr_created_idx" ON "letters_of_notice" USING btree ("purchaseRequestId","createdAt");--> statement-breakpoint
CREATE UNIQUE INDEX "pre_canvass_quote_supplier_unique" ON "pre_canvass_quotes" USING btree ("preCanvassId","supplierId");--> statement-breakpoint
CREATE UNIQUE INDEX "procurement_catalog_favorite_user_item_unique" ON "procurement_catalog_favorites" USING btree ("userId","catalogItemId");--> statement-breakpoint
CREATE INDEX "procurement_catalog_favorite_user_idx" ON "procurement_catalog_favorites" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "procurement_catalog_favorite_item_idx" ON "procurement_catalog_favorites" USING btree ("catalogItemId");--> statement-breakpoint
CREATE INDEX "procurement_catalog_active_idx" ON "procurement_catalog_items" USING btree ("isActive");--> statement-breakpoint
CREATE INDEX "document_entity_created_idx" ON "procurement_documents" USING btree ("entityType","entityId","createdAt");--> statement-breakpoint
CREATE INDEX "document_uploader_created_idx" ON "procurement_documents" USING btree ("uploadedById","createdAt");--> statement-breakpoint
CREATE INDEX "pr_item_pr_idx" ON "purchase_request_items" USING btree ("purchaseRequestId");--> statement-breakpoint
CREATE INDEX "pr_item_catalog_idx" ON "purchase_request_items" USING btree ("catalogItemId");--> statement-breakpoint
CREATE INDEX "pr_requester_status_idx" ON "purchase_requests" USING btree ("requestedById","status");--> statement-breakpoint
CREATE INDEX "pr_office_status_idx" ON "purchase_requests" USING btree ("officeId","status");--> statement-breakpoint
CREATE INDEX "supplier_evaluation_supplier_date_idx" ON "supplier_evaluations" USING btree ("supplierId","evaluatedAt");--> statement-breakpoint
CREATE UNIQUE INDEX "supplier_quote_rfq_supplier_unique" ON "supplier_quotations" USING btree ("rfqId","supplierId");--> statement-breakpoint
CREATE UNIQUE INDEX "supplier_tag_assignment_unique" ON "supplier_tag_assignments" USING btree ("supplierId","supplierTagId");--> statement-breakpoint
CREATE INDEX "supplier_tag_assignment_supplier_idx" ON "supplier_tag_assignments" USING btree ("supplierId");--> statement-breakpoint
CREATE INDEX "supplier_tag_assignment_tag_idx" ON "supplier_tag_assignments" USING btree ("supplierTagId");--> statement-breakpoint
CREATE INDEX "supplier_tag_active_idx" ON "supplier_tags" USING btree ("isActive");--> statement-breakpoint
CREATE INDEX "supplier_company_idx" ON "suppliers" USING btree ("companyName");--> statement-breakpoint
CREATE INDEX "test_record_archive_status_idx" ON "test_record_archives" USING btree ("cleanedAt","archivedAt");--> statement-breakpoint
CREATE INDEX "correction_entity_created_idx" ON "workflow_corrections" USING btree ("entityType","entityId","createdAt");--> statement-breakpoint
CREATE INDEX "correction_assignee_status_idx" ON "workflow_corrections" USING btree ("assignedToId","status");--> statement-breakpoint
CREATE INDEX "notification_recipient_read_created_idx" ON "workflow_notifications" USING btree ("recipientUserId","readAt","createdAt");