CREATE TABLE "best_value_policies" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "best_value_policies_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"policyCode" varchar(64) NOT NULL,
	"name" varchar(180) NOT NULL,
	"version" integer NOT NULL,
	"isActive" integer DEFAULT 1 NOT NULL,
	"totalWeight" numeric(7, 2) NOT NULL,
	"createdById" integer NOT NULL,
	"createdAt" timestamp DEFAULT now() NOT NULL,
	"deactivatedAt" timestamp
);
--> statement-breakpoint
CREATE TABLE "best_value_policy_criteria" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "best_value_policy_criteria_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"policyId" integer NOT NULL,
	"criterionKey" varchar(80) NOT NULL,
	"label" varchar(180) NOT NULL,
	"description" text,
	"weight" numeric(7, 2) NOT NULL,
	"sortOrder" integer NOT NULL,
	"createdAt" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE UNIQUE INDEX "best_value_policy_code_version_unique" ON "best_value_policies" USING btree ("policyCode","version");--> statement-breakpoint
CREATE INDEX "best_value_policy_active_created_idx" ON "best_value_policies" USING btree ("isActive","createdAt");--> statement-breakpoint
CREATE UNIQUE INDEX "best_value_policy_criterion_unique" ON "best_value_policy_criteria" USING btree ("policyId","criterionKey");--> statement-breakpoint
CREATE INDEX "best_value_policy_criteria_policy_order_idx" ON "best_value_policy_criteria" USING btree ("policyId","sortOrder");