CREATE TABLE "supplier_evaluation_approvals" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "supplier_evaluation_approvals_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"supplierEvaluationId" integer NOT NULL,
	"approvedById" integer NOT NULL,
	"approverName" varchar(180) NOT NULL,
	"approverDesignation" varchar(180) NOT NULL,
	"consentStatement" text NOT NULL,
	"signatureDigest" varchar(128) NOT NULL,
	"approvedAt" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "supplier_evaluation_approvals_supplierEvaluationId_unique" UNIQUE("supplierEvaluationId")
);
--> statement-breakpoint
ALTER TABLE "supplier_evaluations" ADD COLUMN "reportedPurchaseRequestNumber" varchar(80);--> statement-breakpoint
ALTER TABLE "supplier_evaluations" ADD COLUMN "urgentPurchaseRequestReason" text;--> statement-breakpoint
ALTER TABLE "supplier_evaluations" ADD COLUMN "urgentPurchaseRequestUpdatedById" integer;--> statement-breakpoint
ALTER TABLE "supplier_evaluations" ADD COLUMN "urgentPurchaseRequestUpdatedAt" timestamp;--> statement-breakpoint
CREATE INDEX "supplier_evaluation_approval_approver_date_idx" ON "supplier_evaluation_approvals" USING btree ("approvedById","approvedAt");