CREATE TABLE "procurement_signatories" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "procurement_signatories_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"fullName" varchar(180) NOT NULL,
	"designation" varchar(160) NOT NULL,
	"mayRequest" integer DEFAULT 0 NOT NULL,
	"mayApprove" integer DEFAULT 0 NOT NULL,
	"isActive" integer DEFAULT 1 NOT NULL,
	"createdById" integer NOT NULL,
	"createdAt" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "purchase_requests" ADD COLUMN "requestedSignatoryId" integer;--> statement-breakpoint
ALTER TABLE "purchase_requests" ADD COLUMN "requestedSignatoryName" varchar(180);--> statement-breakpoint
ALTER TABLE "purchase_requests" ADD COLUMN "approvedSignatoryId" integer;--> statement-breakpoint
ALTER TABLE "purchase_requests" ADD COLUMN "approvedSignatoryName" varchar(180);--> statement-breakpoint
ALTER TABLE "purchase_requests" ADD COLUMN "approvedSignatoryDesignation" varchar(160);--> statement-breakpoint
CREATE INDEX "procurement_signatory_active_idx" ON "procurement_signatories" USING btree ("isActive","mayRequest","mayApprove");