CREATE TABLE "procurement_catalog_saved_items" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "procurement_catalog_saved_items_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"userId" integer NOT NULL,
	"catalogItemId" integer NOT NULL,
	"quantity" numeric(12, 2) DEFAULT '1.00' NOT NULL,
	"createdAt" timestamp DEFAULT now() NOT NULL,
	"updatedAt" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE UNIQUE INDEX "procurement_catalog_saved_user_item_unique" ON "procurement_catalog_saved_items" USING btree ("userId","catalogItemId");--> statement-breakpoint
CREATE INDEX "procurement_catalog_saved_user_idx" ON "procurement_catalog_saved_items" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "procurement_catalog_saved_item_idx" ON "procurement_catalog_saved_items" USING btree ("catalogItemId");