ALTER TABLE "procurewise"."purchase_requests" ADD COLUMN IF NOT EXISTS "assignedOfficerId" integer;

CREATE TABLE IF NOT EXISTS "procurewise"."purchase_request_decisions" (
	"id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
	"purchaseRequestId" integer NOT NULL,
	"decisionType" varchar(64) NOT NULL,
	"fromStatus" varchar(64) NOT NULL,
	"toStatus" varchar(64) NOT NULL,
	"reason" text NOT NULL,
	"remarks" text,
	"performedById" integer NOT NULL,
	"performedByRole" varchar(64) NOT NULL,
	"documentId" integer,
	"createdAt" timestamp DEFAULT now() NOT NULL
);

CREATE INDEX IF NOT EXISTS "pr_decision_pr_idx" ON "procurewise"."purchase_request_decisions" USING btree ("purchaseRequestId","createdAt");

CREATE TABLE IF NOT EXISTS "procurewise"."rfq_number_assignments" (
	"id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
	"fiscalYear" integer NOT NULL,
	"sequenceNumber" integer NOT NULL,
	"formattedRfqNumber" varchar(48) NOT NULL,
	"assignmentMode" varchar(32) NOT NULL,
	"urgentReason" text,
	"assignedById" integer NOT NULL,
	"assignedAt" timestamp DEFAULT now() NOT NULL,
	"purchaseRequestId" integer,
	"rfqId" integer,
	"status" varchar(32) DEFAULT 'active' NOT NULL,
	CONSTRAINT "rfq_number_assignments_formattedRfqNumber_unique" UNIQUE("formattedRfqNumber")
);

CREATE INDEX IF NOT EXISTS "rfq_num_year_seq_idx" ON "procurewise"."rfq_number_assignments" USING btree ("fiscalYear","sequenceNumber");
CREATE INDEX IF NOT EXISTS "rfq_num_pr_idx" ON "procurewise"."rfq_number_assignments" USING btree ("purchaseRequestId");

CREATE TABLE IF NOT EXISTS "procurewise"."form_templates" (
	"id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
	"templateKey" varchar(64) NOT NULL,
	"version" integer NOT NULL,
	"displayName" varchar(180) NOT NULL,
	"status" varchar(32) DEFAULT 'draft' NOT NULL,
	"configurationJson" json NOT NULL,
	"createdById" integer NOT NULL,
	"updatedById" integer NOT NULL,
	"approvedById" integer,
	"createdAt" timestamp DEFAULT now() NOT NULL,
	"updatedAt" timestamp DEFAULT now() NOT NULL,
	"activatedAt" timestamp
);

CREATE UNIQUE INDEX IF NOT EXISTS "form_template_key_version_unique" ON "procurewise"."form_templates" USING btree ("templateKey","version");
CREATE INDEX IF NOT EXISTS "form_template_key_status_idx" ON "procurewise"."form_templates" USING btree ("templateKey","status");
