CREATE TABLE "procurewise"."form_templates" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "procurewise"."form_templates_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"templateKey" varchar(64) NOT NULL,
	"version" integer NOT NULL,
	"displayName" varchar(180) NOT NULL,
	"status" varchar(32) DEFAULT 'draft' NOT NULL,
	"configurationJson" json NOT NULL,
	"createdById" integer NOT NULL,
	"updatedById" integer NOT NULL,
	"approvedById" integer,
	"createdAt" timestamp DEFAULT now() NOT NULL,
	"updatedAt" timestamp DEFAULT now() NOT NULL,
	"activatedAt" timestamp
);
--> statement-breakpoint
CREATE TABLE "procurewise"."pmr_historical_records" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "procurewise"."pmr_historical_records_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"recordKey" varchar(80) NOT NULL,
	"sourceWorkbook" varchar(255) NOT NULL,
	"sourceRow" integer NOT NULL,
	"fiscalYear" integer NOT NULL,
	"month" varchar(24),
	"endUser" varchar(180),
	"positionDesignation" varchar(180),
	"fundCode" varchar(80),
	"fundClass" varchar(80),
	"prNumber" varchar(80) NOT NULL,
	"modality" varchar(120),
	"item" text,
	"quantity" numeric(14, 3),
	"unitOfIssue" varchar(60),
	"unitBudget" numeric(14, 2),
	"estimatedTotal" numeric(14, 2),
	"unitLcrb" numeric(14, 2),
	"total" numeric(14, 2),
	"purpose" text,
	"office" varchar(180),
	"lonReceivedDate" varchar(80),
	"bacAwardApprovedDate" varchar(80),
	"poContractDate" varchar(80),
	"poContractDateReceived" varchar(80),
	"deliveryDate" varchar(80),
	"supplier" varchar(240),
	"iarDate" varchar(80),
	"sectionCodeDepartment" varchar(120),
	"releasedDate" varchar(80),
	"status" varchar(80),
	"remarks" text,
	"obrNumber" varchar(120),
	"rfqsPrinted" varchar(80),
	"salesChargeInvoice" varchar(160),
	"importedAt" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "pmr_historical_records_recordKey_unique" UNIQUE("recordKey")
);
--> statement-breakpoint
CREATE TABLE "procurewise"."purchase_request_decisions" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "procurewise"."purchase_request_decisions_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"purchaseRequestId" integer NOT NULL,
	"decisionType" varchar(64) NOT NULL,
	"fromStatus" varchar(64) NOT NULL,
	"toStatus" varchar(64) NOT NULL,
	"reason" text NOT NULL,
	"remarks" text,
	"performedById" integer NOT NULL,
	"performedByRole" varchar(64) NOT NULL,
	"documentId" integer,
	"createdAt" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "procurewise"."rfq_number_assignments" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "procurewise"."rfq_number_assignments_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"fiscalYear" integer NOT NULL,
	"sequenceNumber" integer NOT NULL,
	"formattedRfqNumber" varchar(48) NOT NULL,
	"assignmentMode" varchar(32) NOT NULL,
	"urgentReason" text,
	"assignedById" integer NOT NULL,
	"assignedAt" timestamp DEFAULT now() NOT NULL,
	"purchaseRequestId" integer,
	"rfqId" integer,
	"status" varchar(32) DEFAULT 'active' NOT NULL,
	CONSTRAINT "rfq_number_assignments_formattedRfqNumber_unique" UNIQUE("formattedRfqNumber")
);
--> statement-breakpoint
ALTER TABLE "procurewise"."letters_of_notice" ADD COLUMN "demandDueDate" timestamp;--> statement-breakpoint
ALTER TABLE "procurewise"."letters_of_notice" ADD COLUMN "demandReminderDate" timestamp;--> statement-breakpoint
ALTER TABLE "procurewise"."letters_of_notice" ADD COLUMN "demandReminderSentAt" timestamp;--> statement-breakpoint
ALTER TABLE "procurewise"."procurement_settings" ADD COLUMN "appearanceTheme" varchar(32) DEFAULT 'light' NOT NULL;--> statement-breakpoint
ALTER TABLE "procurewise"."procurement_settings" ADD COLUMN "appearanceFont" varchar(40) DEFAULT 'public_sans' NOT NULL;--> statement-breakpoint
ALTER TABLE "procurewise"."procurement_settings" ADD COLUMN "appearanceFontScale" varchar(16) DEFAULT '100' NOT NULL;--> statement-breakpoint
ALTER TABLE "procurewise"."procurement_settings" ADD COLUMN "appearanceDensity" varchar(16) DEFAULT 'comfortable' NOT NULL;--> statement-breakpoint
ALTER TABLE "procurewise"."procurement_settings" ADD COLUMN "appearanceAccent" varchar(16) DEFAULT 'maroon' NOT NULL;--> statement-breakpoint
ALTER TABLE "procurewise"."procurement_settings" ADD COLUMN "appearanceCorners" varchar(16) DEFAULT 'sharp' NOT NULL;--> statement-breakpoint
ALTER TABLE "procurewise"."procurement_settings" ADD COLUMN "appearanceReducedMotion" integer DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE "procurewise"."purchase_requests" ADD COLUMN "assignedOfficerId" integer;--> statement-breakpoint
ALTER TABLE "procurewise"."suppliers" ADD COLUMN "philgepsRegistrationNumber" varchar(120);--> statement-breakpoint
ALTER TABLE "procurewise"."suppliers" ADD COLUMN "philgepsRegistrationDate" timestamp;--> statement-breakpoint
ALTER TABLE "procurewise"."suppliers" ADD COLUMN "philgepsExpirationDate" timestamp;--> statement-breakpoint
ALTER TABLE "procurewise"."users" ADD COLUMN "officeName" varchar(180);--> statement-breakpoint
ALTER TABLE "procurewise"."form_templates" ADD CONSTRAINT "form_templates_createdById_users_id_fk" FOREIGN KEY ("createdById") REFERENCES "procurewise"."users"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "procurewise"."form_templates" ADD CONSTRAINT "form_templates_updatedById_users_id_fk" FOREIGN KEY ("updatedById") REFERENCES "procurewise"."users"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "procurewise"."form_templates" ADD CONSTRAINT "form_templates_approvedById_users_id_fk" FOREIGN KEY ("approvedById") REFERENCES "procurewise"."users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "procurewise"."purchase_request_decisions" ADD CONSTRAINT "purchase_request_decisions_purchaseRequestId_purchase_requests_id_fk" FOREIGN KEY ("purchaseRequestId") REFERENCES "procurewise"."purchase_requests"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "procurewise"."purchase_request_decisions" ADD CONSTRAINT "purchase_request_decisions_performedById_users_id_fk" FOREIGN KEY ("performedById") REFERENCES "procurewise"."users"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "procurewise"."purchase_request_decisions" ADD CONSTRAINT "purchase_request_decisions_documentId_procurement_documents_id_fk" FOREIGN KEY ("documentId") REFERENCES "procurewise"."procurement_documents"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "procurewise"."rfq_number_assignments" ADD CONSTRAINT "rfq_number_assignments_assignedById_users_id_fk" FOREIGN KEY ("assignedById") REFERENCES "procurewise"."users"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "procurewise"."rfq_number_assignments" ADD CONSTRAINT "rfq_number_assignments_purchaseRequestId_purchase_requests_id_fk" FOREIGN KEY ("purchaseRequestId") REFERENCES "procurewise"."purchase_requests"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "procurewise"."rfq_number_assignments" ADD CONSTRAINT "rfq_number_assignments_rfqId_rfqs_id_fk" FOREIGN KEY ("rfqId") REFERENCES "procurewise"."rfqs"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "form_template_key_version_unique" ON "procurewise"."form_templates" USING btree ("templateKey","version");--> statement-breakpoint
CREATE INDEX "form_template_key_status_idx" ON "procurewise"."form_templates" USING btree ("templateKey","status");--> statement-breakpoint
CREATE INDEX "pmr_history_year_idx" ON "procurewise"."pmr_historical_records" USING btree ("fiscalYear");--> statement-breakpoint
CREATE INDEX "pmr_history_pr_idx" ON "procurewise"."pmr_historical_records" USING btree ("prNumber");--> statement-breakpoint
CREATE INDEX "pmr_history_supplier_idx" ON "procurewise"."pmr_historical_records" USING btree ("supplier");--> statement-breakpoint
CREATE INDEX "pr_decision_pr_idx" ON "procurewise"."purchase_request_decisions" USING btree ("purchaseRequestId","createdAt");--> statement-breakpoint
CREATE INDEX "rfq_num_year_seq_idx" ON "procurewise"."rfq_number_assignments" USING btree ("fiscalYear","sequenceNumber");--> statement-breakpoint
CREATE INDEX "rfq_num_pr_idx" ON "procurewise"."rfq_number_assignments" USING btree ("purchaseRequestId");--> statement-breakpoint
ALTER TABLE "procurewise"."abstracts_of_canvass" ADD CONSTRAINT "abstracts_of_canvass_preCanvassId_pre_canvasses_id_fk" FOREIGN KEY ("preCanvassId") REFERENCES "procurewise"."pre_canvasses"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "procurewise"."abstracts_of_canvass" ADD CONSTRAINT "abstracts_of_canvass_recommendedSupplierId_suppliers_id_fk" FOREIGN KEY ("recommendedSupplierId") REFERENCES "procurewise"."suppliers"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "procurewise"."abstracts_of_canvass" ADD CONSTRAINT "abstracts_of_canvass_preparedById_users_id_fk" FOREIGN KEY ("preparedById") REFERENCES "procurewise"."users"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "procurewise"."abstracts_of_canvass" ADD CONSTRAINT "abstracts_of_canvass_decidedById_users_id_fk" FOREIGN KEY ("decidedById") REFERENCES "procurewise"."users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "procurewise"."app_ppmp_entries" ADD CONSTRAINT "app_ppmp_entries_officeId_offices_id_fk" FOREIGN KEY ("officeId") REFERENCES "procurewise"."offices"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "procurewise"."app_ppmp_entries" ADD CONSTRAINT "app_ppmp_entries_objectOfExpenditureId_objects_of_expenditure_id_fk" FOREIGN KEY ("objectOfExpenditureId") REFERENCES "procurewise"."objects_of_expenditure"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "procurewise"."app_ppmp_entries" ADD CONSTRAINT "app_ppmp_entries_catalogItemId_procurement_catalog_items_id_fk" FOREIGN KEY ("catalogItemId") REFERENCES "procurewise"."procurement_catalog_items"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "procurewise"."app_ppmp_entries" ADD CONSTRAINT "app_ppmp_entries_preparedById_users_id_fk" FOREIGN KEY ("preparedById") REFERENCES "procurewise"."users"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "procurewise"."audit_trails" ADD CONSTRAINT "audit_trails_performedById_users_id_fk" FOREIGN KEY ("performedById") REFERENCES "procurewise"."users"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "procurewise"."bac_transmittals" ADD CONSTRAINT "bac_transmittals_purchaseRequestId_purchase_requests_id_fk" FOREIGN KEY ("purchaseRequestId") REFERENCES "procurewise"."purchase_requests"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "procurewise"."bac_transmittals" ADD CONSTRAINT "bac_transmittals_preparedById_users_id_fk" FOREIGN KEY ("preparedById") REFERENCES "procurewise"."users"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "procurewise"."best_value_policies" ADD CONSTRAINT "best_value_policies_createdById_users_id_fk" FOREIGN KEY ("createdById") REFERENCES "procurewise"."users"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "procurewise"."best_value_policy_criteria" ADD CONSTRAINT "best_value_policy_criteria_policyId_best_value_policies_id_fk" FOREIGN KEY ("policyId") REFERENCES "procurewise"."best_value_policies"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "procurewise"."budget_allotments" ADD CONSTRAINT "budget_allotments_officeId_offices_id_fk" FOREIGN KEY ("officeId") REFERENCES "procurewise"."offices"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "procurewise"."budget_allotments" ADD CONSTRAINT "budget_allotments_objectOfExpenditureId_objects_of_expenditure_id_fk" FOREIGN KEY ("objectOfExpenditureId") REFERENCES "procurewise"."objects_of_expenditure"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "procurewise"."budget_allotments" ADD CONSTRAINT "budget_allotments_createdById_users_id_fk" FOREIGN KEY ("createdById") REFERENCES "procurewise"."users"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "procurewise"."delivery_receipts" ADD CONSTRAINT "delivery_receipts_purchaseOrderId_purchase_orders_id_fk" FOREIGN KEY ("purchaseOrderId") REFERENCES "procurewise"."purchase_orders"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "procurewise"."delivery_receipts" ADD CONSTRAINT "delivery_receipts_receivedById_users_id_fk" FOREIGN KEY ("receivedById") REFERENCES "procurewise"."users"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "procurewise"."historical_prices" ADD CONSTRAINT "historical_prices_supplierId_suppliers_id_fk" FOREIGN KEY ("supplierId") REFERENCES "procurewise"."suppliers"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "procurewise"."historical_prices" ADD CONSTRAINT "historical_prices_purchaseOrderId_purchase_orders_id_fk" FOREIGN KEY ("purchaseOrderId") REFERENCES "procurewise"."purchase_orders"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "procurewise"."historical_prices" ADD CONSTRAINT "historical_prices_recordedById_users_id_fk" FOREIGN KEY ("recordedById") REFERENCES "procurewise"."users"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "procurewise"."letters_of_notice" ADD CONSTRAINT "letters_of_notice_purchaseRequestId_purchase_requests_id_fk" FOREIGN KEY ("purchaseRequestId") REFERENCES "procurewise"."purchase_requests"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "procurewise"."letters_of_notice" ADD CONSTRAINT "letters_of_notice_supplierId_suppliers_id_fk" FOREIGN KEY ("supplierId") REFERENCES "procurewise"."suppliers"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "procurewise"."letters_of_notice" ADD CONSTRAINT "letters_of_notice_issuedById_users_id_fk" FOREIGN KEY ("issuedById") REFERENCES "procurewise"."users"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "procurewise"."mcdm_recommendations" ADD CONSTRAINT "mcdm_recommendations_preCanvassId_pre_canvasses_id_fk" FOREIGN KEY ("preCanvassId") REFERENCES "procurewise"."pre_canvasses"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "procurewise"."mcdm_recommendations" ADD CONSTRAINT "mcdm_recommendations_recommendedSupplierId_suppliers_id_fk" FOREIGN KEY ("recommendedSupplierId") REFERENCES "procurewise"."suppliers"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "procurewise"."mcdm_recommendations" ADD CONSTRAINT "mcdm_recommendations_createdById_users_id_fk" FOREIGN KEY ("createdById") REFERENCES "procurewise"."users"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "procurewise"."pmr_logs" ADD CONSTRAINT "pmr_logs_purchaseOrderId_purchase_orders_id_fk" FOREIGN KEY ("purchaseOrderId") REFERENCES "procurewise"."purchase_orders"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "procurewise"."pmr_logs" ADD CONSTRAINT "pmr_logs_loggedById_users_id_fk" FOREIGN KEY ("loggedById") REFERENCES "procurewise"."users"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "procurewise"."pre_canvass_quotes" ADD CONSTRAINT "pre_canvass_quotes_preCanvassId_pre_canvasses_id_fk" FOREIGN KEY ("preCanvassId") REFERENCES "procurewise"."pre_canvasses"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "procurewise"."pre_canvass_quotes" ADD CONSTRAINT "pre_canvass_quotes_supplierId_suppliers_id_fk" FOREIGN KEY ("supplierId") REFERENCES "procurewise"."suppliers"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "procurewise"."pre_canvasses" ADD CONSTRAINT "pre_canvasses_purchaseRequestId_purchase_requests_id_fk" FOREIGN KEY ("purchaseRequestId") REFERENCES "procurewise"."purchase_requests"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "procurewise"."pre_canvasses" ADD CONSTRAINT "pre_canvasses_preparedById_users_id_fk" FOREIGN KEY ("preparedById") REFERENCES "procurewise"."users"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "procurewise"."procurement_catalog_favorites" ADD CONSTRAINT "procurement_catalog_favorites_userId_users_id_fk" FOREIGN KEY ("userId") REFERENCES "procurewise"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "procurewise"."procurement_catalog_favorites" ADD CONSTRAINT "procurement_catalog_favorites_catalogItemId_procurement_catalog_items_id_fk" FOREIGN KEY ("catalogItemId") REFERENCES "procurewise"."procurement_catalog_items"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "procurewise"."procurement_catalog_saved_items" ADD CONSTRAINT "procurement_catalog_saved_items_userId_users_id_fk" FOREIGN KEY ("userId") REFERENCES "procurewise"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "procurewise"."procurement_catalog_saved_items" ADD CONSTRAINT "procurement_catalog_saved_items_catalogItemId_procurement_catalog_items_id_fk" FOREIGN KEY ("catalogItemId") REFERENCES "procurewise"."procurement_catalog_items"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "procurewise"."procurement_documents" ADD CONSTRAINT "procurement_documents_uploadedById_users_id_fk" FOREIGN KEY ("uploadedById") REFERENCES "procurewise"."users"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "procurewise"."procurement_settings" ADD CONSTRAINT "procurement_settings_updatedById_users_id_fk" FOREIGN KEY ("updatedById") REFERENCES "procurewise"."users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "procurewise"."procurement_signatories" ADD CONSTRAINT "procurement_signatories_createdById_users_id_fk" FOREIGN KEY ("createdById") REFERENCES "procurewise"."users"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "procurewise"."purchase_orders" ADD CONSTRAINT "purchase_orders_purchaseRequestId_purchase_requests_id_fk" FOREIGN KEY ("purchaseRequestId") REFERENCES "procurewise"."purchase_requests"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "procurewise"."purchase_orders" ADD CONSTRAINT "purchase_orders_rfqId_rfqs_id_fk" FOREIGN KEY ("rfqId") REFERENCES "procurewise"."rfqs"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "procurewise"."purchase_orders" ADD CONSTRAINT "purchase_orders_preCanvassId_pre_canvasses_id_fk" FOREIGN KEY ("preCanvassId") REFERENCES "procurewise"."pre_canvasses"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "procurewise"."purchase_orders" ADD CONSTRAINT "purchase_orders_supplierId_suppliers_id_fk" FOREIGN KEY ("supplierId") REFERENCES "procurewise"."suppliers"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "procurewise"."purchase_orders" ADD CONSTRAINT "purchase_orders_generatedById_users_id_fk" FOREIGN KEY ("generatedById") REFERENCES "procurewise"."users"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "procurewise"."purchase_orders" ADD CONSTRAINT "purchase_orders_approvedById_users_id_fk" FOREIGN KEY ("approvedById") REFERENCES "procurewise"."users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "procurewise"."purchase_request_items" ADD CONSTRAINT "purchase_request_items_purchaseRequestId_purchase_requests_id_fk" FOREIGN KEY ("purchaseRequestId") REFERENCES "procurewise"."purchase_requests"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "procurewise"."purchase_request_items" ADD CONSTRAINT "purchase_request_items_catalogItemId_procurement_catalog_items_id_fk" FOREIGN KEY ("catalogItemId") REFERENCES "procurewise"."procurement_catalog_items"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "procurewise"."purchase_requests" ADD CONSTRAINT "purchase_requests_requestedSignatoryId_procurement_signatories_id_fk" FOREIGN KEY ("requestedSignatoryId") REFERENCES "procurewise"."procurement_signatories"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "procurewise"."purchase_requests" ADD CONSTRAINT "purchase_requests_approvedSignatoryId_procurement_signatories_id_fk" FOREIGN KEY ("approvedSignatoryId") REFERENCES "procurewise"."procurement_signatories"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "procurewise"."purchase_requests" ADD CONSTRAINT "purchase_requests_officeId_offices_id_fk" FOREIGN KEY ("officeId") REFERENCES "procurewise"."offices"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "procurewise"."purchase_requests" ADD CONSTRAINT "purchase_requests_objectOfExpenditureId_objects_of_expenditure_id_fk" FOREIGN KEY ("objectOfExpenditureId") REFERENCES "procurewise"."objects_of_expenditure"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "procurewise"."purchase_requests" ADD CONSTRAINT "purchase_requests_requestedById_users_id_fk" FOREIGN KEY ("requestedById") REFERENCES "procurewise"."users"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "procurewise"."purchase_requests" ADD CONSTRAINT "purchase_requests_ppmpEntryId_app_ppmp_entries_id_fk" FOREIGN KEY ("ppmpEntryId") REFERENCES "procurewise"."app_ppmp_entries"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "procurewise"."purchase_requests" ADD CONSTRAINT "purchase_requests_procurementReviewedById_users_id_fk" FOREIGN KEY ("procurementReviewedById") REFERENCES "procurewise"."users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "procurewise"."purchase_requests" ADD CONSTRAINT "purchase_requests_assignedOfficerId_users_id_fk" FOREIGN KEY ("assignedOfficerId") REFERENCES "procurewise"."users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "procurewise"."purchase_requests" ADD CONSTRAINT "purchase_requests_administrativeApprovedById_users_id_fk" FOREIGN KEY ("administrativeApprovedById") REFERENCES "procurewise"."users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "procurewise"."purchase_requests" ADD CONSTRAINT "purchase_requests_budgetReviewedById_users_id_fk" FOREIGN KEY ("budgetReviewedById") REFERENCES "procurewise"."users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "procurewise"."purchase_requests" ADD CONSTRAINT "purchase_requests_supplyReviewedById_users_id_fk" FOREIGN KEY ("supplyReviewedById") REFERENCES "procurewise"."users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "procurewise"."purchase_requests" ADD CONSTRAINT "purchase_requests_bacReviewedById_users_id_fk" FOREIGN KEY ("bacReviewedById") REFERENCES "procurewise"."users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "procurewise"."quotation_abstracts" ADD CONSTRAINT "quotation_abstracts_rfqId_rfqs_id_fk" FOREIGN KEY ("rfqId") REFERENCES "procurewise"."rfqs"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "procurewise"."quotation_abstracts" ADD CONSTRAINT "quotation_abstracts_recommendedSupplierId_suppliers_id_fk" FOREIGN KEY ("recommendedSupplierId") REFERENCES "procurewise"."suppliers"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "procurewise"."quotation_abstracts" ADD CONSTRAINT "quotation_abstracts_preparedById_users_id_fk" FOREIGN KEY ("preparedById") REFERENCES "procurewise"."users"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "procurewise"."quotation_abstracts" ADD CONSTRAINT "quotation_abstracts_approvedById_users_id_fk" FOREIGN KEY ("approvedById") REFERENCES "procurewise"."users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "procurewise"."rfqs" ADD CONSTRAINT "rfqs_purchaseRequestId_purchase_requests_id_fk" FOREIGN KEY ("purchaseRequestId") REFERENCES "procurewise"."purchase_requests"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "procurewise"."rfqs" ADD CONSTRAINT "rfqs_createdById_users_id_fk" FOREIGN KEY ("createdById") REFERENCES "procurewise"."users"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "procurewise"."supplier_evaluation_approvals" ADD CONSTRAINT "supplier_evaluation_approvals_supplierEvaluationId_supplier_evaluations_id_fk" FOREIGN KEY ("supplierEvaluationId") REFERENCES "procurewise"."supplier_evaluations"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "procurewise"."supplier_evaluation_approvals" ADD CONSTRAINT "supplier_evaluation_approvals_approvedById_users_id_fk" FOREIGN KEY ("approvedById") REFERENCES "procurewise"."users"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "procurewise"."supplier_evaluations" ADD CONSTRAINT "supplier_evaluations_supplierId_suppliers_id_fk" FOREIGN KEY ("supplierId") REFERENCES "procurewise"."suppliers"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "procurewise"."supplier_evaluations" ADD CONSTRAINT "supplier_evaluations_purchaseOrderId_purchase_orders_id_fk" FOREIGN KEY ("purchaseOrderId") REFERENCES "procurewise"."purchase_orders"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "procurewise"."supplier_evaluations" ADD CONSTRAINT "supplier_evaluations_purchaseRequestId_purchase_requests_id_fk" FOREIGN KEY ("purchaseRequestId") REFERENCES "procurewise"."purchase_requests"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "procurewise"."supplier_evaluations" ADD CONSTRAINT "supplier_evaluations_urgentPurchaseRequestUpdatedById_users_id_fk" FOREIGN KEY ("urgentPurchaseRequestUpdatedById") REFERENCES "procurewise"."users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "procurewise"."supplier_evaluations" ADD CONSTRAINT "supplier_evaluations_officeId_offices_id_fk" FOREIGN KEY ("officeId") REFERENCES "procurewise"."offices"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "procurewise"."supplier_evaluations" ADD CONSTRAINT "supplier_evaluations_evaluatedById_users_id_fk" FOREIGN KEY ("evaluatedById") REFERENCES "procurewise"."users"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "procurewise"."supplier_quotations" ADD CONSTRAINT "supplier_quotations_rfqId_rfqs_id_fk" FOREIGN KEY ("rfqId") REFERENCES "procurewise"."rfqs"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "procurewise"."supplier_quotations" ADD CONSTRAINT "supplier_quotations_supplierId_suppliers_id_fk" FOREIGN KEY ("supplierId") REFERENCES "procurewise"."suppliers"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "procurewise"."supplier_tag_assignments" ADD CONSTRAINT "supplier_tag_assignments_supplierId_suppliers_id_fk" FOREIGN KEY ("supplierId") REFERENCES "procurewise"."suppliers"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "procurewise"."supplier_tag_assignments" ADD CONSTRAINT "supplier_tag_assignments_supplierTagId_supplier_tags_id_fk" FOREIGN KEY ("supplierTagId") REFERENCES "procurewise"."supplier_tags"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "procurewise"."supplier_tag_assignments" ADD CONSTRAINT "supplier_tag_assignments_assignedById_users_id_fk" FOREIGN KEY ("assignedById") REFERENCES "procurewise"."users"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "procurewise"."supplier_tags" ADD CONSTRAINT "supplier_tags_createdById_users_id_fk" FOREIGN KEY ("createdById") REFERENCES "procurewise"."users"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "procurewise"."suppliers" ADD CONSTRAINT "suppliers_createdById_users_id_fk" FOREIGN KEY ("createdById") REFERENCES "procurewise"."users"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "procurewise"."test_record_archives" ADD CONSTRAINT "test_record_archives_ppmpEntryId_app_ppmp_entries_id_fk" FOREIGN KEY ("ppmpEntryId") REFERENCES "procurewise"."app_ppmp_entries"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "procurewise"."test_record_archives" ADD CONSTRAINT "test_record_archives_archivedById_users_id_fk" FOREIGN KEY ("archivedById") REFERENCES "procurewise"."users"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "procurewise"."workflow_corrections" ADD CONSTRAINT "workflow_corrections_requestedById_users_id_fk" FOREIGN KEY ("requestedById") REFERENCES "procurewise"."users"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "procurewise"."workflow_corrections" ADD CONSTRAINT "workflow_corrections_assignedToId_users_id_fk" FOREIGN KEY ("assignedToId") REFERENCES "procurewise"."users"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "procurewise"."workflow_notifications" ADD CONSTRAINT "workflow_notifications_recipientUserId_users_id_fk" FOREIGN KEY ("recipientUserId") REFERENCES "procurewise"."users"("id") ON DELETE cascade ON UPDATE no action;